### ISSUE TITLE
libmediainfo and libwebkit2gtk are not bundled with the AppImage

### ISSUE THREAD

**Issue by prateekmedia** [harmonoid/harmonoid#108]
Failed to load dynamic library libwinmedia, taken from AppImage/appimage.github.io#2745

**Comment by prateekmedia** [comment]
Taken after seeing AppImage/appimage.github.io#2745

**Comment by dym-sh** [comment]
fixed it with `sudo apt install libmediainfo-dev`

**Comment by prateekmedia** [comment]
@dym-sh If that's the case then It might be only due to the fact that libmediainfo is not bundled with appimage.

**Comment by gaetan1903** [comment]
sudo pacman -Ss libmediainfo
after run this, i have 
![image](https://user-images.githubusercontent.com/43904633/136706333-08e8201f-8d5c-46ee-aa17-9276fd4ae713.png)

**Comment by prateekmedia** [comment]
@gaetan1903 Download libwebkit2gtk as mentioned in README for .deb package dependencies(applies to all packages).

**Comment by alexmercerind** [comment]
I don't think this is relevant anymore since we are using `libmpv` now.
