### ISSUE TITLE
Arabic Language is not showed Correctly

### ISSUE THREAD

**Issue by jawadalkassim** [harmonoid/harmonoid#122]
**Expected behavior**
Show Arabic language properly

![Screenshot from 2021-10-07 20-48-36](https://user-images.githubusercontent.com/48631694/136437410-9e1cbbbf-0c24-48c2-b3b3-0597192d8213.png)

**Desktop (please complete the following information):**
 - OS: Pop OS 21.04 Linux
 - Browser Firefox
 - Version 93

**Comment by alexmercerind** [comment]
Thanks a lot for the report. 
I will try to see what I can do.

**Comment by raitonoberu** [comment]
Adding one of the [Arabic fonts](https://github.com/emadomedher/google-fonts-arabic/tree/master/lib/fonts) may fix the issue.

**Comment by alexmercerind** [comment]
@jawadalkassim this issue should be fixed now, we have now switched to a more wider font-face. A lot of big-changes & UI revamps.

Now, we use `libmpv` for playback & parsing. Latest release & downloads: [v0.2.0](https://github.com/harmonoid/harmonoid/releases/tag/v0.2.0).

<table>
<tr>
<td>
<img src='https://github.com/harmonoid/harmonoid/raw/assets/linux_full/0.jpeg?raw=true'></img>
</td>
<td>
<img src='https://github.com/harmonoid/harmonoid/raw/assets/linux_full/4.jpeg?raw=true'></img>
</td>
</tr>
</table>
