### ISSUE TITLE
Problems with window movement

### ISSUE THREAD

**Issue by agileAlligator** [harmonoid/harmonoid#130]
Floaty window movement in latest version of Windows 10

**To Reproduce**
1. Try to drag window

**Expected behavior**
Moves properly with the cursor

**Observed behavior"
Cursor clones itself and floats off with the window, generally visible lag while dragging the window

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 (latest update as of 19/10/2021)

Edit: Disabling windows acrylic blur seems to fix the issue.

Edit 2: Seems like a windows issue, you cannot fix it as a dev....

**Comment by alexmercerind** [comment]
Thanks for the report. This issue will be fixed in Windows 11 :) Let's keep issue opened to keep future comers informed.

Thanks.

**Comment by agileAlligator** [comment]
I upgraded to Windows 11, it is indeed fixed

**Comment by TENX-S** [comment]
It comes again, on Windows 11 :(

**Comment by alexmercerind** [comment]
> It comes again, on Windows 11 :(

New release will feature a new UI & will no longer use `flutter_acrylic`. A mature & more consistent experience will be there. I will release soon in a while.

**Comment by agileAlligator** [comment]
> It comes again, on Windows 11 :(

I have no issues with this, maybe there is a problem on your end?
