### ISSUE TITLE
Play and search youtube playlists

### ISSUE THREAD

**Issue by agileAlligator** [harmonoid/harmonoid#131]
Maybe a toggle button to search playlists, or at least the functionality to copy paste url into the search bar to play the playlist. I have several playlists on youtube I would like to play but currently cannot.

**Comment by alexmercerind** [comment]
Added in [v0.2.2 Levels](https://github.com/harmonoid/harmonoid/releases/tag/v0.2.2).
Now you can search & view playlists, artists & albums etc. from YouTube Music. One can even save a YouTube playlist locally.

![](https://github.com/harmonoid/harmonoid/blob/assets/webp/web/search.webp?raw=true)
![](https://github.com/harmonoid/harmonoid/blob/assets/webp/web/playlist.webp?raw=true)
![](https://github.com/harmonoid/harmonoid/blob/assets/webp/web/album.webp?raw=true)
