### ISSUE TITLE
Play through folders

### ISSUE THREAD

**Issue by agileAlligator** [harmonoid/harmonoid#135]
I have a lot of albums, it's a pain to keep switching them and also a pain to make a huge playlist. Can we have a feature to switch to the next album and also a setting to randomize that?

**Comment by alexmercerind** [comment]
Thanks for the feedback. I'm currently having bit of time shortage to continue on the project. There's a lot coming soon. Currently #134 is also pending, taskbar controls for Windows / MPRIS controls for Linux & a lot more bug-fixes + other features.

Thankyou.

**Comment by alexmercerind** [comment]
A big update has been released: [v0.2.9](https://github.com/harmonoid/harmonoid/releases/tag/v0.2.9).

Mentioned things have been implemented for all platforms.
