### ISSUE TITLE
Allow me to login to take advantage of my Premium

### ISSUE THREAD

**Issue by kfmadrane** [harmonoid/harmonoid#137]
maybe a feature to download like the music app , but at least login so it can sync up with what i already listen to.

**Comment by mytja** [comment]
Ummm.
I have to say that YouTube login is quite hard to crack. Also, this app's goal is not to become a streaming service, as this would require API keys etc.
If you have YouTube Premium, why don't you use YouTube's app or YouTube Vanced???

**Comment by kfmadrane** [comment]
None of the linux application seem to allow me to log in. Either there is no feature for it or google tells me the application is unsafe.
I understand that that is not the direction you want to take, its a pity tho i realy like your ui.
Thanks for the speedy response though.

**Comment by mytja** [comment]
> None of the linux application seem to allow me to log in. Either there is no feature for it or google tells me the application is unsafe. I understand that that is not the direction you want to take, its a pity tho i realy like your ui. Thanks for the speedy response though.

I'm so sorry that we cannot provide you this... It definitly would be possible, but a lot of effort would be needed, so it's just a pain for everyone, as Google can with one click make our solution not work overnight... YouTubeDL already has such login
About the UI, @alexmercerind worked really hard on it, and I think he'd be happy of your praise.
