### ISSUE TITLE
Ability to search YouTube with duration / length filters, sorting by popularity/views/etc.

### ISSUE THREAD

**Issue by nekohayo** [harmonoid/harmonoid#138]
For my planned usage scenario for this app, I would like to be able to limit/filter my YouTube searches to results that are over an hour long, so I can find the nature sounds, vocal trance mixes, synthwave mixes, operas, etc.

I sometimes would also like to be able to sort by popularity or views count.

**Comment by alexmercerind** [comment]
A big update has just been released: [v0.2.9](https://github.com/harmonoid/harmonoid/releases/tag/v0.2.9).

These features are related to YouTube & not YouTube Music, which is something I'm currently not planning on.
