### ISSUE TITLE
Could not fetch the youtube audio stream

### ISSUE THREAD

**Issue by dzarkV** [harmonoid/harmonoid#140]
I'm getting that when I use the youtube option.

PD: the app is great!

**Comment by mytja** [comment]
Yeah, this is an issue with current backend. The maintainer hasn't updated it's backend to latest PyTube version. Anyways, you can build latest commit from source and use that. It uses better method of fetching audio streams and better UI.

**Comment by mytja** [comment]
I built latest commit on Linux if anybody wants it: [harmonoid-linux.zip](https://github.com/harmonoid/harmonoid/files/7780822/harmonoid-linux.zip)

**Comment by jmdeaugustine** [comment]
> I built latest commit on Linux if anybody wants it: [harmonoid-linux.zip](https://github.com/harmonoid/harmonoid/files/7780822/harmonoid-linux.zip)
> 
> EDIT: I also built latest commit on Windows [harmonoid-windows.zip](https://github.com/harmonoid/harmonoid/files/7785984/harmonoid-windows.zip)

Hello, I'd really like to use this :).  I downloaded and unzipped that folder in linux mint. But i'm not sure what to do with it or even what to search.  How can I use this latest commit? I am ok in the terminal if you would kindly share a command for using that latest commit. 

Thank you!

**Comment by mytja** [comment]
What I did was this:
```
sudo ln -s /home/mytja/harmonoid/harmonoid /usr/bin/harmonoid
```

You replace `/home/mytja/harmonoid/harmonoid` with path you downloaded Harmonoid executable (in my case `/home/mytja/harmonoid`) + name of executable (must be `harmonoid`)

`/usr/bin/harmonoid` is path to which this file will be linked.

This will allow you to execute file from command line & it also got picked up by my application manager (GUI)

**Comment by jmdeaugustine** [comment]
I tried your command with my own file path and got this error: 
"failed to create symbolic link ‘/usr/bin/harmonoid’: File exists"

So I added an f to force the link: 
sudo ln -sf /home/ginger/Downloads/harmonoid/harmonoid /usr/bin/harmonoid

and it worked!  but now the program won't open. Nothing happens when I click the icon
and I get this message when I run in the terminal : 

"ginger@ginger-HP-15-Notebook-PC:~$ harmonoid
harmonoid: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/ginger/Downloads/harmonoid/lib/libflutter_media_metadata_plugin.so)
harmonoid: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /home/ginger/Downloads/harmonoid/lib/libflutter_media_metadata_plugin.so)
"

I'm gunna try to uninstall and try again

**Comment by mytja** [comment]
It's most likely a fault on my side.

I use Arch and Arch comes with newest packages, so they are incompatible with your stable Ubuntu/Mint/Debian packages.

I will compile on Ubuntu.

**Comment by mytja** [comment]
This is built on Ubuntu 20.04 LTS. I hope it works. [harmonoid-linux-ubuntu.zip](https://github.com/harmonoid/harmonoid/files/7820046/harmonoid-linux-ubuntu.zip)

**Comment by raitonoberu** [comment]
> harmonoid-linux-ubuntu.zip

I successfully ran it on Arch after installing some libs with `paru -S libmediainfo webkit2gtk`. However, youtube playback does not work. Logs:
<details>

```
flutter: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("navigationEndpoint")
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:68)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:115)
#2      TrackExtension.recommendations (package:harmonoid/core/youtubemusic.dart:1)
<asynchronous suspension>
#3      YouTubeStateController.updateRecommendations (package:harmonoid/interface/changenotifiers.dart:272)
<asynchronous suspension>

flutter: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("navigationEndpoint")
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:68)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:115)
#2      TrackExtension.recommendations (package:harmonoid/core/youtubemusic.dart:1)
<asynchronous suspension>
#3      YouTubeStateController.updateRecommendations (package:harmonoid/interface/changenotifiers.dart:272)
<asynchronous suspension>

flutter: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("navigationEndpoint")
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:68)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:115)
#2      TrackExtension.recommendations (package:harmonoid/core/youtubemusic.dart:1)
<asynchronous suspension>
#3      YouTubeStateController.updateRecommendations (package:harmonoid/interface/changenotifiers.dart:272)
<asynchronous suspension>

flutter: RangeError (length): Invalid value: Only valid value is 0: -1
flutter: #0      TrackExtension.recommendations (package:harmonoid/core/youtubemusic.dart:1)
<asynchronous suspension>
#1      YouTubeStateController.updateRecommendations (package:harmonoid/interface/changenotifiers.dart:272)
<asynchronous suspension>

flutter: 137
flutter: 248
flutter: 399
flutter: 136
flutter: 247
flutter: 398
flutter: 135
flutter: 244
flutter: 397
flutter: 134
flutter: 243
flutter: 396
flutter: 133
flutter: 242
flutter: 395
flutter: 160
flutter: 278
flutter: 394
flutter: 139
flutter: 140
flutter: 249
flutter: 250
flutter: 251
flutter: https://rr4---sn-hxb54vo-v8cs.googlevideo.com/videoplayback?expire=1641569044&ei=tAbYYenLI4K5yQXJz6aAAw&ip=112.922.7.971&id=o-ABVopc-tiKNuYRD2M0bQrse1hgArHbO3rE9dyqDVvyGT&itag=251&source=youtube&requiressl=yes&mh=Na&mm=31%2C29&mn=sn-hxb54vo-v8cs%2Csn-n8v7znss&ms=au%2Crdu&mv=m&mvi=4&pl=22&gcr=ru&initcwndbps=432500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=3212507&dur=202.861&lmt=1621003082607483&mt=1641547016&fvip=12&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgK5nUrYhtC4hVvR8zez-WBBModDt5a4bdH9X2pC2RiV8CIHpENbt_hTRU2W4W2a5YUmKQxiN0OWxChewwW3n9fPor&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgbVINj4Gz4ElHmIYBa-WKDHwRND4ouMxKuXdKLdCCX5ECIHI6ZqL-cbAw-UVFBzMrv4AhPRkWbI_xSqk6Yh7rbLPv
flutter: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("longBylineText")
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:68)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:115)
#2      TrackExtension.recommendations (package:harmonoid/core/youtubemusic.dart:1)
<asynchronous suspension>
#3      YouTubeStateController.updateRecommendations (package:harmonoid/interface/changenotifiers.dart:272)
<asynchronous suspension>

flutter: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("navigationEndpoint")
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:68)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:115)
#2      TrackExtension.recommendations (package:harmonoid/core/youtubemusic.dart:1)
<asynchronous suspension>
#3      YouTubeStateController.updateRecommendations (package:harmonoid/interface/changenotifiers.dart:274)
<asynchronous suspension>

flutter: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("navigationEndpoint")
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:68)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:115)
#2      TrackExtension.recommendations (package:harmonoid/core/youtubemusic.dart:1)
<asynchronous suspension>
#3      YouTubeStateController.updateRecommendations (package:harmonoid/interface/changenotifiers.dart:274)
<asynchronous suspension>

flutter: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("navigationEndpoint")
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:68)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:115)
#2      TrackExtension.recommendations (package:harmonoid/core/youtubemusic.dart:1)
<asynchronous suspension>
#3      YouTubeStateController.updateRecommendations (package:harmonoid/interface/changenotifiers.dart:274)
<asynchronous suspension>

flutter: RangeError (length): Invalid value: Only valid value is 0: -1
flutter: #0      TrackExtension.recommendations (package:harmonoid/core/youtubemusic.dart:1)
<asynchronous suspension>
#1      YouTubeStateController.updateRecommendations (package:harmonoid/interface/changenotifiers.dart:274)
<asynchronous suspension>

flutter: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("navigationEndpoint")
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:68)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:115)
#2      TrackExtension.recommendations (package:harmonoid/core/youtubemusic.dart:1)
<asynchronous suspension>
#3      YouTubeStateController.updateRecommendations (package:harmonoid/interface/changenotifiers.dart:274)
<asynchronous suspension>
```
</details>

Also, if I open the printed url in the browser, it works.

**Comment by mytja** [comment]
Hmmm, it works for me on Arch and Kali. It's really strange. Does it work on older release?

**Comment by raitonoberu** [comment]
The problem seems to be on my side, cuz local files don't work either. This is what I get when trying to open an mp3:
```sh
file:///tmp/source.html:1: CONSOLE JS ERROR SyntaxError: Unexpected EOF
file:///tmp/source.html:1: CONSOLE JS ERROR SyntaxError: Unexpected EOF
```
idk, maybe I still need to install something

**Comment by jmdeaugustine** [comment]
The software center version now works on Mint! Thank you :)

**Comment by dzarkV** [comment]
I used to use it on Android, but I think I'll go for Linux this time. Thanks

> I built latest commit on Linux if anybody wants it: [harmonoid-linux.zip](https://github.com/harmonoid/harmonoid/files/7780822/harmonoid-linux.zip)
> 
> EDIT: I also built latest commit on Windows [harmonoid-windows.zip](https://github.com/harmonoid/harmonoid/files/7785984/harmonoid-windows.zip)

**Comment by alexmercerind** [comment]
Rolling out new Windows release today 🎉. You may [download](https://github.com/harmonoid/harmonoid/releases/tag/v0.1.9) & share your feedback with us at Discord.

Features & changes will be propagated to other platforms soon.

Fixing this issue & greatly improving starting time of the YouTube songs. Also added ability to store YouTube music along local songs in local playlists to play on the go. Changelog is available at the same link.
