### ISSUE TITLE
Scanning for opus files is slow

### ISSUE THREAD

**Issue by 2ndemosthenes** [harmonoid/harmonoid#142]
**Describe the bug**
While scanning for files, MP3 files are found pretty fast but scanning opus files take forever, specially if you have a larger collection. 

One of the few players which doesn't have this problem is Rocket Player, which uses TagLib.

**To Reproduce**
1. Add a directory full of opus files (at least 1000)
2. Click on Refresh

**Expected behavior**
Scanning for opus files should be as fast as mp3 files.

**Smartphone (please complete the following information):**
 - Device: Huawei Y7 Prime 2018
 - OS: Android 8

**Comment by alexmercerind** [comment]
The Android version has been re-written majorly, please try out [v0.2.9](https://github.com/harmonoid/harmonoid/releases/tag/v0.2.9).

It's not a big concern. We use native `MediaMetadataRetriever` class from Android API. 

Scanning only happens one-time, it's worth the wait! 😁 Still, it doesn't block you from listening while indexing happens in background.
