### ISSUE TITLE
Sign into YouTube Music account to sync library

### ISSUE THREAD

**Issue by SleepDaemon** [harmonoid/harmonoid#143]
**Sign into Youtube Music**

It would be great to sign into my account and have all my playlists and what not, so I can easily find them and play them.

**Comment by alexmercerind** [comment]
Thanks a lot for the request. In future, we will provide a way to import a whole YouTube playlist inside the app to save it for future or play directly.

I haven't been much active on the project, but a lot of stuff is coming soon with the next update!

Thankyou.

**Comment by SleepDaemon** [comment]
> Thanks a lot for the request. In future, we will provide a way to import a whole YouTube playlist inside the app to save it for future or play directly.
> 
> I haven't been much active on the project, but a lot of stuff is coming soon with the next update!
> 
> Thankyou.

 thanks, But what I mean by login into account is that having access to my liked playlist which has all music i've liked. I don't use custom playlist, I just go to my history on YT Music and play songs from there.

**Comment by alexmercerind** [comment]
Closing in favor of #228.
