### ISSUE TITLE
Error "Could not fetch YouTube Audio Stream" when trying to play any youtube audio.

### ISSUE THREAD

**Issue by QuakeString** [harmonoid/harmonoid#145]
Searching any song on youtube is working, but when I trying to play any song on youtube it saying "**Could not fetch YouTube Audio Stream**".

This is AppImage Package

Here is error screenshot
![2022-01-24_09-03](https://user-images.githubusercontent.com/5375918/150718373-18f7408c-dd9e-44b2-bed4-870a9efc7054.png)

This is terminal output when I'm trying to the same action
![Screenshot_20220124_091017](https://user-images.githubusercontent.com/5375918/150718303-aac2d03b-a3fb-4b86-bb69-ae539fa666d2.png)

Here is app Detail
![Screenshot_20220124_090825](https://user-images.githubusercontent.com/5375918/150718150-93a2a9d0-eaba-43cd-b95b-5ecac559fb1c.png)

Here is my system detail
![Screenshot_20220124_090752](https://user-images.githubusercontent.com/5375918/150718108-25b951d9-3824-4ca0-be89-3f958cb5e8ec.png)

**Comment by alexmercerind** [comment]
Thanks for the report.

We desperately need a new release (last one was 6 months ago). I'm really working on some big changes & refactor to the project.

**Comment by SleepDaemon** [comment]
I've also have same issue
![image](https://user-images.githubusercontent.com/88533953/151005364-60b96158-d1c6-4f09-929a-474a28f3f8a7.png)

**Comment by mytja** [comment]
> I've also have same issue ![image](https://user-images.githubusercontent.com/88533953/151005364-60b96158-d1c6-4f09-929a-474a28f3f8a7.png)

It's because of YouTube. YouTube broke functionality of [PyTube](https://github.com/pytube/pytube) a few days ago and so it doesn't work. But @alexmercerind is already brewing a new release that would get rid of entire server, and thus will be much more stable than by using (not-so-well maintained) PyTube, so we need just a little patience. Meanwhile, you can use releases I personally built a few commits ago and are available [here](https://github.com/harmonoid/harmonoid/issues/140#issuecomment-1001625335) (or for Linux [here](https://github.com/harmonoid/harmonoid/issues/140#issuecomment-1006330661))

**Comment by SleepDaemon** [comment]
> > I've also have same issue ![image](https://user-images.githubusercontent.com/88533953/151005364-60b96158-d1c6-4f09-929a-474a28f3f8a7.png)
> 
> It's because of YouTube. YouTube broke functionality of [PyTube](https://github.com/pytube/pytube) a few days ago and so it doesn't work. But @alexmercerind is already brewing a new release that would get rid of entire server, and thus will be much more stable than by using (not-so-well maintained) PyTube, so we need just a little patience. Meanwhile, you can use releases I personally built a few commits ago and are available [here](https://github.com/harmonoid/harmonoid/issues/140#issuecomment-1001625335) (or for Linux [here](https://github.com/harmonoid/harmonoid/issues/140#issuecomment-1006330661))

I downloaded your commits and works fine, replaced it with the download from 6 months ago.
@alexmercerind maybe you should use it?

**Comment by alexmercerind** [comment]
> > > I've also have same issue ![image](https://user-images.githubusercontent.com/88533953/151005364-60b96158-d1c6-4f09-929a-474a28f3f8a7.png)
> > 
> > 
> > It's because of YouTube. YouTube broke functionality of [PyTube](https://github.com/pytube/pytube) a few days ago and so it doesn't work. But @alexmercerind is already brewing a new release that would get rid of entire server, and thus will be much more stable than by using (not-so-well maintained) PyTube, so we need just a little patience. Meanwhile, you can use releases I personally built a few commits ago and are available [here](https://github.com/harmonoid/harmonoid/issues/140#issuecomment-1001625335) (or for Linux [here](https://github.com/harmonoid/harmonoid/issues/140#issuecomment-1006330661))
> 
> I downloaded your commits and works fine, replaced it with the download from 6 months ago. @alexmercerind maybe you should use it?

Today I plan to release a new Windows build with completely rewritten YouTube playback system & its 5x faster than before & playback time is identical to YouTube webapp.

**Comment by SleepDaemon** [comment]
> > > > I've also have same issue ![image](https://user-images.githubusercontent.com/88533953/151005364-60b96158-d1c6-4f09-929a-474a28f3f8a7.png)
> > > 
> > > 
> > > It's because of YouTube. YouTube broke functionality of [PyTube](https://github.com/pytube/pytube) a few days ago and so it doesn't work. But @alexmercerind is already brewing a new release that would get rid of entire server, and thus will be much more stable than by using (not-so-well maintained) PyTube, so we need just a little patience. Meanwhile, you can use releases I personally built a few commits ago and are available [here](https://github.com/harmonoid/harmonoid/issues/140#issuecomment-1001625335) (or for Linux [here](https://github.com/harmonoid/harmonoid/issues/140#issuecomment-1006330661))
> > 
> > 
> > I downloaded your commits and works fine, replaced it with the download from 6 months ago. @alexmercerind maybe you should use it?
> 
> Today I plan to release a new Windows build with completely rewritten YouTube playback system & its 5x faster than before & playback time is identical to YouTube webapp.

ayyyyy nice, also i just found a new song i like through the app but i couldnt find a way to open it in YT Music and like it.

**Comment by alexmercerind** [comment]
Great! Now app will behave a lot lot like official client (and plan is to get close in experience with time), now recommended songs will be automatically added to now playing. Plus, you can save YouTube songs in local playlists (along your local songs) to play everything together, I'm really loving experience. Sharing the update in a while, documenting changelog.

**Comment by SleepDaemon** [comment]
> Great! Now app will behave a lot lot like official client (and plan is to get close in experience with time), now recommended songs will be automatically added to now playing. Plus, you can save YouTube songs in local playlists (along your local songs) to play everything together, I'm really loving experience. Sharing the update in a while, documenting changelog.

yeah the recommendation is spot on, I play one song i have from my yt music history and it started recommending other musicians i follow and listen to and new ones as well. I would like the ability to sync everything with my YT Music and so that I don't have to worry of going back and finding all the songs. Another final request is maybe a way to auto update the app? or at least notify user when new update is out.

**Comment by SleepDaemon** [comment]
Another update, the app says "Unknown Year" for when the song or album was released

**Comment by mytja** [comment]
I think this should be closed now
