### ISSUE TITLE
Where does Harmonoid save local playlists as well as any other app data?

### ISSUE THREAD

**Issue by EmanuelLoos** [harmonoid/harmonoid#147]
Is it documented anywhere where app data can be found on the different supported platforms, secifically Android?

I looked under many common paths (also those that are normally not user accessible) but could not find any data about a playlist I created.

I am using a custom ROM (LinageOS 17.1 with microG) with Magisk for root access and F-Droid as app store.

**Comment by mytja** [comment]
https://github.com/harmonoid/harmonoid/blob/master/lib/core/configuration.dart#L43-L52 (have a look at this for [Android](https://pub.dev/documentation/path_provider/latest/path_provider/getExternalStorageDirectory.html)), and saves it to subdirectory called `.Harmonoid`

**Comment by alexmercerind** [comment]
Currently we just store playlists in a `playlists.JSON` file in the first music folder that you added (I'm aware this is not a good thing & it will be changing after next version).

I'm working on some really really **big** changes both user-accessibility & UI wise. Like a proper material UI with adequate amount of animations in it & for desktop, we are switching to MPV based music backend. I have also arranged some iconography for usage within the application.

We will soon be creating a Discord server as-well to talk & plan about the project in detail. Plan is to bring best cross platform music experience, at the moment I'm doing it all myself but I need a bit of help from community in future to add more stuff.

Currently I haven't pushed a lot of code for various reasons. 

_Sneak Peak [Work In Progress]_
![explorer_k5EZWyjoNa](https://user-images.githubusercontent.com/28951144/151236649-d4788ed7-7b32-429c-8d30-8af54fd7f57b.gif)

Equivalent for Linux & Android.

**Comment by alexmercerind** [comment]
I'm very inspirational about the project again & wanna make it great for everyone to use & enjoy their music.

Repository might seem in bit of in-active state & that is because I'm not planning to push all of the code right now since most work done by me is stolen by others or libraries made by me specifically for `Harmonoid` get used by other developers for their own projects without proper credit or appreciation. In summary, open source hasn't been very rewarding for me in general & currently I have decided to keep a segment of app closed source, but this doesn't degrade the privacy/freedom of the app in any-way I promise.

**Comment by EmanuelLoos** [comment]
> work done by me gets stolen by others or libraries made by me specifically for Harmonoid get used by other developers for their own projects without proper credit or appreciation

How does something like this happen with your project licensed under the GPLv3? Wouldn't this be illegal under these conditions?

> In summary, open source hasn't been very rewarding for me in general & currently I have decided to keep a segment of app closed source, but this doesn't degrade the privacy/freedom of the app in any-way I promise.

In the name of free and open source software I am sorry for whatever happened. I find it remarkable that you found it in yourself to continue developing free software (as in freedom). Indeed it does not harm freedom if you keep code private as long as you do not distribute binary versions missing the corresponding source code. This is called private software and is not problematic.

I could be understanding something wrong but I am quite skeptical about keeping a segment of the (distributed) app closed source though. This would harm freedom 1 (the freedom to study the software) and freedom 3 (the freedom to improve the software) of the [Free Software Definiton](https://www.gnu.org/philosophy/free-sw.html#fs-definition). If you mean by keeping a segment closed source that you keep an unpublished segment that you still work on closed source this is more than okay, of course.

**Comment by alexmercerind** [comment]
@EmanuelLoos 

Most of the times just adding a `LICENSE` isn't very helpful, it doesn't ensure the enforcement of the license & people get away with it. It takes time, law knowledge & money to fight for the truth.

People in past have stolen code from OBS, Mastodon or FFmpeg etc. And not even mentioning how companies possibly just get away by not mentioning the open source tools/code they used in their properitary software. 
People in past have cloned this project, and uploaded it into their own repositories by making minor changes and giving no orignal copyright notice.

As of now, I have still planned to release 100% of the source code in this repository (which is 100% of Android app's source code).

For Windows & Linux however, I have created few private (at least for now) packages and shared libraries (DLLs) to use `libmpv` (LGPL & dynamically linked) through `FFI` & other System APIs like SMTC & taskbar thumbnail toolbar controls. Currently I haven't made them open source. 
**Currently I haven't planned if I will make those dependencies (in separate repository) open source or not. If I do, then it would be done right before the release of next version.**
Our builds are auto generated by our GitHub actions CI & I do not compile on my private computer, so most likely I will.

As you may see we have 2 other repositories under this organisation, which were used for media playback/parsing on Windows & Linux. This setup wasn't powerful enough & had many problems.

**Comment by EmanuelLoos** [comment]
Thank you for this insight.

> Most of the times just adding a `LICENSE` isn't very helpful, it doesn't ensure the enforcement of the license & people get away with it. It takes time, law knowledge & money to fight for the truth.

You are right this is a problem. The truth getting acknowledged should not cost so much and it definitely should not cost money.

> As of now, I have still planned to release 100% of the source code in this repository which includes all business logic, UI and state management (which is 100% of Android app's source code).

Great, this means it meets the criteria for F-Droid inclusion.

> For Windows & Linux however, I have created few private (at least for now) packages and shared libraries (DLLs) to use libmpv (LGPL & dynamically linked) through FFI & other System APIs like SMTC & taskbar thumbnail toolbar controls. Currently I haven't made them open source.
> Currently I haven't planned if I will make those dependencies (in separate repository) open source or not. If I do, then it would be done right before the release of next version.

Please keep in mind that there are some people who actually try to never use non-free software if it can be avoided in any practical way. You will not find them using Windows, MacOS, iOS, etc but there are some using GNU/Linux distributions or (forks of) AOSP. These folks would not use your software if it had any non-free dependencies. Software with non-free dependencies also does not get included in the official Debian (main) repositories. Therefore it would be great if these versions could stay completely free. For people using non-free operating systems this type of freedom is probably not that important, of course it would be good everywhere but it is specifically important on platforms that are really trying hard to stay as free as possible.
