### ISSUE TITLE
Metadata shown in the app is mixed up when playing a local playlist of OPUS files from multiple albums in shuffle mode

### ISSUE THREAD

**Issue by EmanuelLoos** [harmonoid/harmonoid#148]
When playing a local playlist of OPUS files from multiple albums in shuffle mode the album covers are mixed up in the app although they are right in the notification.

To reproduce create a local playlist of local OPUS files with an album art in their metadata that includes files from multiple albums in Harmonoid and play it in shuffle mode.

I am using a custom ROM (LinageOS 17.1 with microG) with Magisk for root access and F-Droid as app store.

-----------------------------------------------

EDIT: I just realized that not only the album over but all metadata shown in the app except for the lyrics is wrong.

**Comment by alexmercerind** [comment]
I eventually intend to fork some audio plugin & add my own features to it & fix existing. I really wanted to save myself from touching Java/Kotlin but no more.

**Comment by alexmercerind** [comment]
Addressed in latest release.
