### ISSUE TITLE
Image for Discord RPC

### ISSUE THREAD

**Issue by SleepDaemon** [harmonoid/harmonoid#153]
**Image for Discord RPC**

Take look at Premid, they updated YT Music RPC to show the album cover image in the Presence and when you're not playing any songs it just show the YT Music Logo. You can do the same except instead YT Music logo, use Harmonoid logo.

Harmonoid
![image](https://user-images.githubusercontent.com/88533953/152644130-43daa002-1ee6-4a4c-a596-1ceb4253d3de.png)

PreMiD
![image](https://user-images.githubusercontent.com/88533953/152644195-4c7ada03-bfb4-4f31-a578-e1950e984ee9.png)

**Comment by alexmercerind** [comment]
Thanks a lot for the idea. I had no idea one could even change album art, I thought it was some private API available for Spotify etc.

**Comment by alexmercerind** [comment]
![Screenshot 2022-07-11 170446](https://user-images.githubusercontent.com/28951144/178797372-32bdf990-cd2a-4824-899a-15738140c83b.png)
![Screenshot 2022-07-11 170420](https://user-images.githubusercontent.com/28951144/178797377-994caa20-5ce5-4546-80d3-6c0fbdab2e67.png)

https://github.com/harmonoid/harmonoid/releases/tag/v0.2.5
