### ISSUE TITLE
Follow system proxy settings

### ISSUE THREAD

**Issue by TENX-S** [harmonoid/harmonoid#154]
**Describe the new feature you'd like**

This will be extremely helpful for user lives in China, which blocks by [GFW](https://en.wikipedia.org/wiki/Great_Firewall) (Means we can't access YouTube directly)

**Comment by alexmercerind** [comment]
What should I do to follow proxy settings? I don't have much idea, please feel free to share.
Thankyou.

**Comment by mytja** [comment]
> What should I do to follow proxy settings? I don't have much idea, please feel free to share (or I will research). Thankyou.

Normally you assign environment variables `HTTPS_PROXY` and `HTTP_PROXY`. These environment variables are normally used.

`HTTPS_PROXY` is used, when your final destination URL uses `HTTPS` (note, that proxy URL still can use `HTTP`)
`HTTP_PROXY` is used, when your final destination URL uses `HTTP` (note, that proxy URL can use `HTTPS` afaik)

**Comment by TENX-S** [comment]
https://stackoverflow.com/a/33127042
The third method works on my Windows.

**Comment by TENX-S** [comment]
> > What should I do to follow proxy settings? I don't have much idea, please feel free to share (or I will research). Thankyou.
> 
> Normally you assign environment variables `HTTPS_PROXY` and `HTTP_PROXY`. These environment variables are normally used.
> 
> `HTTPS_PROXY` is used, when your final destination URL uses `HTTPS` (note, that proxy URL still can use `HTTP`) `HTTP_PROXY` is used, when your final destination URL uses `HTTP` (note, that proxy URL can use `HTTPS` afaik)

Using env variables may not be that common case as much as I know in China. We normally use [v2ray](https://github.com/2dust/v2rayN) and [Shadowsocks](https://shadowsocks.org/en/download/clients.html) which not directly set `HTTPS_PROXY` or `HTTP_PROXY` but let you set it manually.

**Comment by mytja** [comment]
I know this is not so related to this issue, but you can now proxy Harmonoid's YouTube requests using [ytm-proxy](https://github.com/harmonoid/ytm-proxy). Have a look at this issue #155.

**Comment by lost4git** [comment]
@alexmercerind  looking forward to it eagerly

**Comment by alexmercerind** [comment]
Now these environment variables are looked for proxy:

Scroll down for download links: https://github.com/harmonoid/harmonoid/releases/tag/v0.2.5

```
http_proxy
https_proxy
no_proxy
HTTP_PROXY
HTTPS_PROXY
NO_PROXY
```

I'm pretty sure all apps/clients set them. Any case, manual setup of environment variables isn't tedious either.
