### ISSUE TITLE
Add tooltips

### ISSUE THREAD

**Issue by Poopooracoocoo** [harmonoid/harmonoid#158]
**Describe the new feature you'd like**
Add tooltips to the interface such as the buttons in the now playing bar, the settings icon and sort icon.
Note that I am using the Windows app.

**Comment by alexmercerind** [comment]
Thanks for the reports. I will make sure to add you in the app credits & you may join our Discord if you wish to follow the development closer.

**Comment by Poopooracoocoo** [comment]
I'd love to join your Discord! No need for credit :P

**Comment by YehudaKremer** [comment]
Hey @Poopooracoocoo 

Tooltips added in version 0.2.1

Thanks for the feature request 👍
