### ISSUE TITLE
Harmonoid hangs after clicking on minimise, restore or maximise on Windows

### ISSUE THREAD

**Issue by Poopooracoocoo** [harmonoid/harmonoid#164]
**Describe the bug**
Harmonoid hangs briefly after clicking on minimise, restore or maximise on Windows

**To Reproduce**
1. Open Harmonoid

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2, build 19044.1466
 - Browser: (not relevant, but running Chrome 88 FWIW...)
 - Version: 0.1.9

**Smartphone (please complete the following information):** N/A

**Comment by alexmercerind** [comment]
Thanks for the report. You mean is there some SIGTERM after closing?
A video or screenshot demonstration will be really helpful.

**Comment by Poopooracoocoo** [comment]
I recorded it with ShareX but realised that you can't actually see when I click. Know how I might capture when I click?

**Comment by alexmercerind** [comment]
Okay I feel I realize what you mean. There's a slight delay when pressing any of the caption buttons.

**Comment by alexmercerind** [comment]
@raitonoberu fixed this! 🚀

**Comment by raitonoberu** [comment]
did i?
