### ISSUE TITLE
Add keyboard navigation to YouTube search

### ISSUE THREAD

**Issue by Poopooracoocoo** [harmonoid/harmonoid#165]
**Describe the new feature you'd like**
![image](https://user-images.githubusercontent.com/51363864/152785210-fffaf9af-d50f-4e54-8e38-14fd81c012d1.png)
I would expect to be able to navigate up and down using my arrow keys.
And for the text in the search bar to change accordingly (without the results changing) and then continuing to input text if I wanted (with search results changing) and then pressing enter to search.

Here's what I mean:

https://user-images.githubusercontent.com/51363864/152787111-997e885c-be51-4945-a0e2-645ada3bc859.mp4
This is a recording of the YouTube Music website.

**Comment by alexmercerind** [comment]
Yeah, again a very critical thing. I'm also habitual of using it on YouTube.

**Comment by YehudaKremer** [comment]
Hello @alexmercerind 
Did someone start working on this? can you assign this to me?

**Comment by alexmercerind** [comment]
Ohh this is really important feature.

**Comment by YehudaKremer** [comment]
on it.
