### ISSUE TITLE
Follow system theme

### ISSUE THREAD

**Issue by Poopooracoocoo** [harmonoid/harmonoid#170]
**Describe the new feature you'd like**

You may add images for extended description.

![image](https://user-images.githubusercontent.com/51363864/152793375-91837ba0-1656-42d1-b9b5-c728a89effc5.png)

**Comment by alexmercerind** [comment]
Added by @YehudaKremer.

Thanks!

Download: [Bug-Bash #1](https://github.com/harmonoid/harmonoid/releases/tag/v0.2.1-hotfix1).
