### ISSUE TITLE
Titlebar looks the same when active and inactive

### ISSUE THREAD

**Issue by Poopooracoocoo** [harmonoid/harmonoid#171]
**Describe the bug**
You cannot discern whether Harmonoid is active or not. Especially when accent coloured window borders are disabled in Windows

**To Reproduce**
1. Open Harmonoid
2. Click outside of the window to make the window inactive

**Expected behavior**
The title and caption buttons would go a shade of gray.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2, build 19044.1466

**Smartphone (please complete the following information):**

**Comment by alexmercerind** [comment]
We don't use native window title-bar, so this is not applicable for us.

**Comment by Poopooracoocoo** [comment]
It should be applicable. :/ There are TONS of custom drawn titlebars such as Chrome, and they implement this. It's difficult to tell whether the window is active or not, especially if you intend to not show a window border at all (which would make Harmonoid stick out amongst other apps)

**Comment by alexmercerind** [comment]
In material design, we use bright white or primary color (in light theme) and grey (in dark theme) for the elevated surfaces like AppBar or Card. 
Changing color of these surfaces will result in incorrect contrast difference with other elements.
Windows & other OSes have different shadow intensities for active/inactive windows which make window appear focused.
Many apps do change color of title-bar but it's not something that we have focus on as of now since what we have is looking good & doesn't need tweaks.

**Comment by Poopooracoocoo** [comment]
Perhaps I should explain what I mean. 

I'm not referring to changing the colours of non-titlebar elements like macOS or GNOME.

The shadow intensity is a really minor detail.

Here's the first example I found on Google Images that doesn't utilise the accent colour: 
![image](https://www.winhelponline.com/blog/wp-content/uploads/w10/w10-title-accent-1.png)

All desktop operating systems make the title and caption buttons grey.

**Comment by Poopooracoocoo** [comment]
@alexmercerind hey have you read my previous message explaining this request?

**Comment by alexmercerind** [comment]
It won't work with our current consistent Material Design implementation.

Title-bar isn't identified as a separate section, it extends into the view on all screens, either sharing area with app-bar or whole screen. Either way, this doesn't interrupt the user's workflow in any way.

https://user-images.githubusercontent.com/28951144/180613629-942ae758-2179-48a8-825f-fc3e918aba0d.mp4

Closing.

**Comment by Poopooracoocoo** [comment]
I still see a distinct titlebar. Even if the colour of the background of it does change, the foreground elements should still be dimmed when inactive. But I respect your decision.
