### ISSUE TITLE
French translation updated

### ISSUE THREAD

**Issue by ejacquemoud** [harmonoid/harmonoid#177]
Hi,

what a nice music software! :)
I just fully updated the French translation. As I'm not familiar with pull requests, I prefer to open an issue with the JSON file attached.

Keep up the good work!

Regards from France,
Etienne J.
[fr_FR.zip](https://github.com/harmonoid/harmonoid/files/8025566/fr_FR.zip)

**Comment by alexmercerind** [comment]
Thanks a lot for the contribution. Appreciate your work.

**Comment by alexmercerind** [comment]
Add you to the about page & README of the project.
