### ISSUE TITLE
external submodules cannot be cloned

### ISSUE THREAD

**Issue by giohappy** [harmonoid/harmonoid#179]
I was trying to build harmonoid but the setup fails because [external](https://github.com/harmonoid/harmonoid/tree/master/external) submodules cannot be cloned, and the folders inside the released soruce code are empty.

**Comment by giohappy** [comment]
my question is only to understand if the project is expected to be build by users or not :)

**Comment by alexmercerind** [comment]
Hello @giohappy !

Sorry for being late, unfortunately it is not possible to compile Harmonoid yet.
We offer compiled executables for Harmonoid for Windows currently, expect Linux too within a week (with more awesome features done for Windows too till then).

After a long run of creating & maintaining open source libraries & apps under my name, I have decided to those libraries used by Harmonoid proprietary.

We will be likely introducing a "premium" variant of the application with more awesome features (now that we are finally moving towards maturity, I will definitely get time to invest more time in cool-side of things. Currently our music indexer indexes 20 files/second, file associations, context menu integration & native media controls for Windows).
Those submodule libraries will be also provided in future under separate pricing & EULAs for the developers/companies wishing to incorporate audio playback / media integration in their projects apart from premium variant of the app.
For now, focusing on important stuff.

**Comment by giohappy** [comment]
thanks @alexmercerind for clarifying.

**Comment by YehudaKremer** [comment]
Hello @alexmercerind 

I also got this problem trying to compile the project on my machine, to see if it can easily use the msix latest version.
I read and understand your answer.

Please see my feature request #193 

Thank you. 👍
