### ISSUE TITLE
Increase the size

### ISSUE THREAD

**Issue by maisondasilva** [harmonoid/harmonoid#184]
Increase the size so that the translation can appear in my language along with youtube

![image](https://user-images.githubusercontent.com/11423362/153753393-f884e44a-8bde-4d2c-899c-ba58f58877f4.png)

Making it open a little wider should solve the problem.

![image](https://user-images.githubusercontent.com/11423362/153753449-3b590cab-af9b-4bbf-9afd-f92845e62ce9.png)

**Comment by alexmercerind** [comment]
Thanks for the report.

I believe #157 will be a better way to target this issue.

I appreciate the feedback.
