### ISSUE TITLE
When I click About learn more the screen turns gray

### ISSUE THREAD

**Issue by maisondasilva** [harmonoid/harmonoid#186]
When I click About learn more the screen turns gray

Window 11

![image](https://user-images.githubusercontent.com/11423362/154250752-bab1f706-117e-4a69-aca3-68d62978ff31.png)

**Comment by alexmercerind** [comment]
I'm sorry to hear that!

I'm aware of this bug, it was introduced after yesterday's changes, because we use GitHub API to show some about page elements.

Thanks for the report.

**Comment by maisondasilva** [comment]
No problem, thanks for the answer, how can I be a contributor to the project like others that appear on the about page?

**Comment by alexmercerind** [comment]
Addressed in latest commit.
