### ISSUE TITLE
Album Artist option on Artist Tab

### ISSUE THREAD

**Issue by ayoob-portfolio** [harmonoid/harmonoid#188]
Currently tracks from the same album are showing under different artists if they have features

![image](https://user-images.githubusercontent.com/87142880/154742779-49142871-56ed-4464-9ebb-a6eb05674f37.png)

**Comment by ayoob-portfolio** [comment]
They are all tagged correctly, they are sorted by Album Artist in RhythmBox

**Comment by alexmercerind** [comment]
> They are all tagged correctly, they are sorted by Album Artist in RhythmBox

Do you mind sharing a file or two which you find should be put together? I'll be really helped. You may attach here or mail at saini123hitesh@gmail.com.

**Comment by alexmercerind** [comment]
Can't reproduce.

There is a new Album-Artist screen possibly to meet your experience requirement.

_(showing available albums from a particular artist)_

![](https://github.com/harmonoid/harmonoid/blob/assets/linux_full/2.jpeg?raw=true)
