### ISSUE TITLE
Option to import playlists

### ISSUE THREAD

**Issue by ayoob-portfolio** [harmonoid/harmonoid#189]

**Comment by sushilfenin** [comment]
that's exactly what i was thinking. what if i could import my spotify playlists. that would be so much better.

**Comment by alexmercerind** [comment]
Added ability to import YouTube playlists without searching. Scroll down for download links. A lot of other things are added.

https://github.com/harmonoid/harmonoid/releases/tag/v0.2.5

![](https://cdn.discordapp.com/attachments/936216526795706368/996089686843998309/harmonoid_QHjqtj56PH.gif)
