### ISSUE TITLE
Update Japanese translaion

### ISSUE THREAD

**Issue by mi875** [harmonoid/harmonoid#190]
It's a very nice music app.
I use the app every day to listen to music.

But I found the several parts which weren't translated.
I translated them except that I don't know the translations.

I hope my work would be helpful.

You can get the ja_JP.json file from the below link.

https://drive.google.com/file/d/1pdOtf2T2cnImgBo-F_C-ZIWaegG5K5ml/view?usp=sharing

**Comment by maisondasilva** [comment]
Closed this case [](https://github.com/alexmercerind)@alexmercerind
[Merge pull request](https://github.com/harmonoid/harmonoid/commit/a4dde25836050ea4cdf6fd6614e7416021d314e7) https://github.com/harmonoid/harmonoid/pull/192 [from maisondasilva/patch-5](https://github.com/harmonoid/harmonoid/commit/a4dde25836050ea4cdf6fd6614e7416021d314e7)

**Comment by mi875** [comment]
Thanks!
