### ISSUE TITLE
Music Library not Populated on Linux (Ubuntu)

### ISSUE THREAD

**Issue by OmariCelestine** [harmonoid/harmonoid#191]
I am currently using Linux (Ubuntu) and I have various MP3 files located in the Music folder but none of it appears in the app.

**Comment by alexmercerind** [comment]
Are you using flatpak?

**Comment by OmariCelestine** [comment]
> Are you using flatpak?

Nope. I used the deb package to install it. I also realised that when I try to add another folder to my __Collection__, nothing happens.

**Comment by alexmercerind** [comment]
https://user-images.githubusercontent.com/28951144/154832147-67e3dfb1-f0d9-4884-b01c-ce4b1bdbf9fd.mp4

As for the performance, I don't compile my own `mpv` or `libmpv-dev` configuration like I do on Windows which makes the performance difference noticeable between the two. I can't seem to reproduce, unless you share in more detail.
Simply 'not works' is not really helpful...
- `mpv`, `libmpv-dev` version.
- `cat ~/.Harmonoid/Configuration.JSON`

can lead us to some direction.

**Comment by OmariCelestine** [comment]
> harmonoid-v0.2.0-indexing-linux.mp4
> 
> As for the performance, I don't compile my own libmpv configuration for Linux like I do on Windows which makes the performance difference noticeable between the two. I can't seem to reproduce, unless you share in more detail. Simply 'not works' is not really helpful...
> 
>     * `mpv`, `libmpv-dev` version.
> 
>     * `cat ~/.Harmonoid/Configuration.JSON`
> 
> 
> can lead us to some direction.

`mpv`, `libmpv-dev` version.
 - `mpv 0.33.1`
 - `libmpv-dev 0.33.1`

`cat ~/.Harmonoid/Configuration.JSON`

```json
{
  "collectionDirectories": [
    "/home/omari/Música\n",
    "/home/omari/Música/Greenz Soca 2017"
  ],
  "languageRegion": 0,
  "accent": 0,
  "themeMode": 2,
  "collectionSortType": 3,
  "collectionOrderType": 0,
  "automaticAccent": false,
  "notificationLyrics": true,
  "collectionSearchRecent": [],
  "discoverSearchRecent": [],
  "discoverRecent": [],
  "showTrackProgressOnTaskbar": false,
  "automaticallyAddOtherSongsFromCollectionToNowPlaying": false,
  "automaticallyShowNowPlayingScreenAfterPlaying": true
}
```

So after restarting the application, the newly added folder to collections now appears.

As for the audio files, it seems that the problems is with the directory path (based on passed experience with other programs). My Operating System is in Spanish to the name of the music folder is now __Música__. Do you think that is possible the problem?

**Comment by alexmercerind** [comment]
Now all the indexing related bugs should be fixed after latest hot-fixes completely. Download: [Bug-Bash #1](https://github.com/harmonoid/harmonoid/releases/tag/v0.2.1-hotfix1).

Thanks.
Feel free to re-open.
