### ISSUE TITLE
Looking for collaborators

### ISSUE THREAD

**Issue by alexmercerind** [harmonoid/harmonoid#196]
**Edit 02/24/2022:**
If you want to be part of the project, you can drop the message below & in that case, I'll share the organization invitation with you & you'll be able to access the private repositories.
I have decided to keep the libraries private & source-code accessible to those who are part of the organization & are regularly contributing to the project.

### Compiling without private packages

See [reasons to not provide private packages openly](#reasons-to-not-provide-private-packages-openly) first.

You can still compile Harmonoid yourself by removing references to following private plugins & replacing them with my following other _already publicly available_ packages:
|Private package |Open-source alternative |Notes |
|------------------|---------------------------|--------|
|[libmpv.dart](https://github.com/harmonoid/libmpv.dart)|[dart_vlc](https://github.com/alexmercerind/dart_vlc) & [flutter_media_metadata](https://github.com/alexmercerind/flutter_media_metadata)| YouTube playback may not work & performance may not be as _tuned_. The resultant bundle size _may_ be larger in size.|
|[smtc-win32](https://github.com/harmonoid/smtc-win32)|[libwinmedia](https://github.com/harmonoid/libwinmedia)| libwinmedia was used in earlier versions of application for media playback & still available under MIT license.|
|[mpris_service.dart](https://github.com/harmonoid/mpris_service.dart)| - | No alternatives available. |
|[harmonoid_visual_assets](https://github.com/harmonoid/harmonoid_visual_assets)| - | Contains iconography & pictures used within the project. You can simply disable.|

### Compiling with private packages

As of now, if you wish to gain access to all the private packages used in [Harmonoid](https://github.com/harmonoid/harmonoid), you may become a [Patreon](https://www.patreon.com/harmonoid). You'll be given all the private packages & lifetime updates to them (+ other perks).

### Reasons to not provide private packages openly

1. I no longer wish to share my code openly for free.
2. I wish to keep the project-specific packages private since I have spent a lot of time on those.
3. The enforcement of open-source licenses is REALLY hard & I can't bear my work getting stolen.
4. After a long run of maintaining open-source packages at [my GitHub profile](https://github.com/alexmercerind), things haven't been very rewarding to say the least. Simply, I no longer want to set my code free in this project.
5. I don't want people to re-distribute (or even sell) my work without my permission on their websites or distribute from their privately owned servers.
6. I don't feel safe putting my work publicly anymore.
7. Users still can compile their own [open version](#compiling-with-private-packages) of the app (if they don't wish to acquire the private packages).
8. I like to get paid for my work & software-development is not _cheap_ either in terms of time spent or resources used.
9. The new version of the app is complete rewrite & it no longer is the _old app_.
10. With no doubt, there are better open-source alternatives present right now. But, we've just started & see [limitations](#limitations) for more details.

<hr></hr>

Currently I'm working on nearly everything & it gets hard to work at following things at once:
- Fixing bugs.
- Testing for bugs & performance.
- UI.
- Native plugin/packages for leveraging playback or parsing of files etc.
- Targeting both YouTube & local music playback/indexing. 

Project will be helped by the presence of developers who are experienced in UI, implementing the features using the fresh plugins that I create for them. If you are not a developer, you can help us by testing the builds & reporting bugs/regressions.

I unfortunate to say don't have much experience in Linux packaging & distribution either. Supporting macOS & other platforms will require even more time (and I don't even have a mac right now). I, as a college student have exams & other study to do, which require time & focus.

Thus, I'm unable to meet all the responsibilities of the project (infact, my other plugins & libraries are more production ready than this app right now).

I'll be really glad if someone decides to join. You may also join the [Discord](https://discord.gg/2Rc3edFWd8) that I made for this project.

I'll share access to all the private repositories in Harmonoid & you can get going with the project until they're more stable & decided to make public.  Few of them don't work with `hot-reload` right now & that's one of the reason why they're not public yet. I currently committed a minimal MIT license for now, which can be used once I make them public.

**Comment by alexmercerind** [comment]
If you wish to make some licensing/distribution changes to the project, feel free to drop a comment.

**Comment by kenvandine** [comment]
I would love to see this published as a snap in the Snap Store.  I'd be happy to do the packaging work, but can't really build the snap myself due to the private submodule.

**Comment by alexmercerind** [comment]
> I would love to see this published as a snap in the Snap Store.  I'd be happy to do the packaging work, but can't really build the snap myself due to the private submodule.  

Greetings!

Hope you're having a good day, it's really really awesome to see someone really experienced (and from Canonical) here.

I use libmpv on Linux for playback/indexing. And... I have no idea why it doesn't seem to free memory on Linux, I can't say if it's a bug in their code, Flutter's code or dart-lang FFI's code. But, same libmpv bindings don't raise that much RAM consistently in Dart CLI but only Flutter.
Or I'll try to create a taglib binding for Dart instead in future.
All I know is that same libmpv.dart works _fine_ on Windows but Linux's RAM just rises overtime. I'm in serious confusion.

![Screenshot_from_2022-02-20_01-08-29.png](https://user-images.githubusercontent.com/28951144/155361094-cb9cd1b7-fe96-40fc-98ad-7bf939177365.png)
_Screenshot shared by a Linux user._


I'm just working on this as a _hobby_ & creating something for _my music needs_. I mainly use my local saved music, but people use YouTube too.

I know your time is limited & I can figure out snap with some docs/experiments.
Again, thanks for noticing the project!
I have sent you the organization invitation & you should be able to see the private repositories here, other than my already public plugins on my profile.

The app uses `mpv` & `libmpv-dev` on Ubuntu & stores music library cache in `~/.Harmonoid`. 

Thanks.

**Comment by YehudaKremer** [comment]
Hello @alexmercerind 
>  Few of them don't work with hot-reload right now 

After commenting the lines [L96-L99](https://github.com/harmonoid/libmpv.dart/blob/fdc5886bd2f81a9e7f9ee1cde324cbe086a9a7fe/lib/src/core/initializer.dart#L96-L99) and [L58-L61](https://github.com/harmonoid/smtc-win32/blob/eab142f3b58ecd9a0ac314e1af163776cd121b79/bindings/system_media_transport_controls.dart/lib/system_media_transport_controls.dart#L58-L61) the hot-reload work for me.

One of the hot-reload functionality is to reload all isolates,
maybe the infinity loop prevents it from doing so.

**Comment by alexmercerind** [comment]
> Hello @alexmercerind
> 
> > Few of them don't work with hot-reload right now
> 
> After commenting the lines [L96-L99](https://github.com/harmonoid/libmpv.dart/blob/fdc5886bd2f81a9e7f9ee1cde324cbe086a9a7fe/lib/src/core/initializer.dart#L96-L99) and [L58-L61](https://github.com/harmonoid/smtc-win32/blob/eab142f3b58ecd9a0ac314e1af163776cd121b79/bindings/system_media_transport_controls.dart/lib/system_media_transport_controls.dart#L58-L61) the hot-reload work for me.
> 
> One of the hot-reload functionality is to reload all isolates, maybe the infinity loop prevents it from doing so.

Hello @YehudaKremer, thanks for the ideas.

I recently experimented with non-isolate based event loop & it seems to _work_ (with no noticeable difference). Maybe I can force that for debug mode.
When passing `timeout` as `0`, it works as in "event polling".
```dart
Timer.periodic(const Duration(milliseconds: 10), (_) {
  final event = mpv.mpv_wait_for_event(handle, 0);
});
```
Surely, this isn't that performant, but can be something which can work in debug mode.

**Comment by brijeshsoni1300** [comment]
i want to be the part of the project
