### ISSUE TITLE
Update Simplified Chinese translaion

### ISSUE THREAD

**Issue by ALILEX-1** [harmonoid/harmonoid#203]
It's a very nice music app.

But I found the several parts which weren't translated.I translated them ，hope my work would be helpful.

You can get the zh_CN.json file from the below link
[https://drive.google.com/file/d/13A8klghvpM1V2vKYUPNsTaWDXm_r72Ij/view?usp=sharing](url)

**Comment by alexmercerind** [comment]
I think it's available now.

Thankyou 🙏
