### ISSUE TITLE
add VK.COM musics 

### ISSUE THREAD

**Issue by doseeare** [harmonoid/harmonoid#210]
**Describe the new feature you'd like**

is that possible to add VK.COM music library? 

VK.COM has API where we can get music's. If that possible i can do it.

**Comment by alexmercerind** [comment]
Thanks for the feedback!
I'll have a look & try to add.

**Comment by raitonoberu** [comment]
VK Music is great, it's much faster and easier to work with. But it cannot become the main source of music for two reasons:

1. As far as I know, 90% of the music is not available outside of Russia and the CIS. Use a VPN and see for yourself.
2. Authorization is required for this. Let's admit that VK is quite unpopular in the rest of the world.

If the author ever wants to support adding music sources other than YouTube music, I will definitely take care of VK support.

**Comment by alexmercerind** [comment]
Restricting the project goals.
