### ISSUE TITLE
[Critical] Handle long path on Windows when indexing & avoid listing errors

### ISSUE THREAD

**Issue by alexmercerind** [harmonoid/harmonoid#214]
See https://github.com/dart-lang/sdk/issues/27825.
<hr></hr>

**Describe the bug:**
Adding long file-path or `Directory` which can lead to a sub-directory or sub-file having long path can break the indexing.

To circumvent, append the `\\?\` string at the ahead of file path. 

**Example case:**
```dart
import 'dart:io';

void main(List<String> args) {
  final prefix = Platform.isWindows ? r'\\?\' : '';
  Directory(prefix +
          'D:\\Soundtrack\\Puella Magi Madoka Magica\\Puella Magi Madoka Magica The Beginning Story & The Eternal Story ED Single - Hikari Furu [Anime Edition] (FLAC)\\Puella Magi Madoka Magica The Beginning Story & The Eternal Story ED Single - Hikari Furu [Anime Edition] (FLAC)')
      .list(
    recursive: true,
    followLinks: false,
  )
      .listen((event) {
    print(event);
  }).onError((_) {
    print(_);
  });
}
```

**Expected workaround:**
Replace all instances of `dart:io`'s file system related calls (including `delete`, `list`) with some sub-classed solution which handles these kind of edge-cases. Thing to note here is that resulting file-paths will also be having a `\\?\` at start of the string.
Another thing to be fixed is that... replace all instances of `Directory.listSync` with something that wraps around `Completer` & uses `Directory.list` instead, which results in it just not simply dying after experiencing a "access denied" or something.

Seriously, why do I feel again & again that Dart/Flutter is not ready for some serious stuff?

**Comment by Sombian** [comment]
thanks!

**Comment by alexmercerind** [comment]
> thanks!

Thanks for the report!
