### ISSUE TITLE
Adding a directory on a TrueNAS CIFS file share fails, causes crash on startup

### ISSUE THREAD

**Issue by shirleymarquez** [harmonoid/harmonoid#224]
**Describe the bug**

Adding a shared directory on a TrueNAS server that does not have an assigned drive letter fails. On add it just quietly fails, but then the application crashes on startup every time.

**To Reproduce**

1. Go to Settings
2. Click Add New Folder
3. Navigate to a network folder in the Select Folder window

No music gets added.
Later, quit and restart Harmonoid, getting this error:

![2022-03-01](https://user-images.githubusercontent.com/9728024/156291534-04bcc70c-275a-4269-bb60-73c6ddcc27e5.png)

**Expected behavior**

Directory gets added and music from the directory is available to play.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 21H2 build 19044.1526
 - Browser: Microsoft Edge
 - Version: 98.0.1108.62 (Official build) (64-bit)

**Comment by alexmercerind** [comment]
Hello @shirleymarquez !
Thanks a lot for filing the bug. I'll get back to this & let you know soon. I had prepended  `\\?\` to the path for handling long-path on Windows. I'll handle this case separately in the code.

Thanks again.

**Comment by alexmercerind** [comment]
Fixed in [Bug-Bash #1 v0.2.1-hotfix1](https://github.com/harmonoid/harmonoid/releases/tag/v0.2.1-hotfix1).

Please try the latest version. I hope you won't experience the problem anymore.

Thankyou very much, we are still a _work in progress_ app & there's a lot to come with time.
