### ISSUE TITLE
SetupIconFile=MyProgSetup.ico

### ISSUE THREAD

**Issue by maisondasilva** [harmonoid/harmonoid#227]
Add icon in program

SetupIconFile=MyProgSetup.ico

![image](https://user-images.githubusercontent.com/11423362/156390419-356fea22-881c-450c-ad91-118ffd9a3341.png)

**Comment by maisondasilva** [comment]
https://jrsoftware.org/ishelp/index.php?topic=setup_setupiconfile

**Comment by YehudaKremer** [comment]
Hello @maisondasilva 

Thanks again for your report and solution 👍 
I added the icon in next version https://github.com/harmonoid/harmonoid-nightly/releases/tag/8b08f5d

![](https://user-images.githubusercontent.com/946652/158030090-7fbbe28d-e65b-4b78-a5a0-0125f7dd9234.png)

**Comment by maisondasilva** [comment]
@YehudaKremer Could you tell me which step to add the icons you made, in addition to what I went through for me to pass on to Samuel do virus upload

https://github.com/SamuelTulach/VirusTotalUploader/issues/103

Line 23

https://github.com/SamuelTulach/VirusTotalUploader/blob/master/inno_setup.iss

**Comment by alexmercerind** [comment]
@maisondasilva have a look at commit 77246401316827dbe4a5a90491aa74c36f1f0022.

Thanks.

**Comment by maisondasilva** [comment]
@YehudaKremer Yes I saw it I thought I sent something else I already sent a patch, thanks https://github.com/SamuelTulach/VirusTotalUploader/pull/104/files
