### ISSUE TITLE
Exception on launch: type 'Null' is not a subtype of type 'int'

### ISSUE THREAD

**Issue by damywise** [harmonoid/harmonoid#233]
**Describe the bug**
App shows exception when launched

**To Reproduce**
1. Install [harmonoid-windows-setup.exe](https://github.com/harmonoid/harmonoid/releases/download/v0.2.1-hotfix1/harmonoid-windows-setup.exe) v0.2.1-hotfix1 or the previous version
2. Launch it
3. See error

**Expected behavior**
App working, not showing exception

**Screenshots**
![image](https://user-images.githubusercontent.com/25608913/157656690-598aa932-6a7a-46f9-a876-51a7af81b26a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by alexmercerind** [comment]
Old cache is not compatible with new versions. Delete `.Harmonoid` folder in your home folder. Expect breaking changes anytime as of now.
Thanks.

**Comment by alexmercerind** [comment]
Was your issue resolved?

Delete a folder like this & let me know.
![image](https://user-images.githubusercontent.com/28951144/157895205-56a37911-c1e3-4d50-9970-8f4fe4d2db78.png)

**Comment by damywise** [comment]
Oh, yeah it was resolved yesterday, sorry I didn't reply.
