### ISSUE TITLE
Local files show "buffering" and stutter

### ISSUE THREAD

**Issue by fapdash** [harmonoid/harmonoid#238]
**Describe the bug**
I play local files (mp3 and flac files on an internal SSD) and they are buffering, causing the music to stop while the player is buffering and the album icon to flicker.
It is best triggered through jumping to another section in the track but it will also happen randomly during normal playback.

**To Reproduce**
1. Start playing a local mp3 or flac file
2. Either just keep it playing and wait or skip to another section in the track, this seems to trigger the issue more often

**Expected behavior**
Playback for local music files should never stop and buffer.

**Screenshots**

https://user-images.githubusercontent.com/459631/158243134-d2ae9a7f-b007-42ce-8cd8-0254fcfa6938.mp4

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: Version 99.0.4844.51 (Official Build) (64-bit)

**Comment by alexmercerind** [comment]
Thanks for the feedback!
I'll let you know once we fix it. I had reduced demuxer cache to reduce RAM usage, but unfortunately I made it too low.

**Comment by alexmercerind** [comment]
Hello @fapdash,

I have fixed this issue in the latest commit, please install the nightly version: https://github.com/harmonoid/harmonoid-nightly/releases/tag/c130f1a.

Thanks!

Keeping this issue opened until next stable release (have some other stuff to fix too).

**Comment by fapdash** [comment]
Verified the fix in [c130f1a](https://github.com/harmonoid/harmonoid-nightly/releases/tag/c130f1a), thank you :)

**Comment by alexmercerind** [comment]
Now on stable.
Download: [Release v0.2.1 - Bug-Bash #2](https://github.com/harmonoid/harmonoid/releases/tag/v0.2.1-hotfix2)
