### ISSUE TITLE
Music starts to play for a short moment if player was closed while playing audio

### ISSUE THREAD

**Issue by fapdash** [harmonoid/harmonoid#239]
**Describe the bug**
When I close the player while it is playing audio and then open it again there is a short moment directly after the start where it plays music.

**To Reproduce**
1. Start playing a local file
2. Close the player by clicking o the "X"
3. Reopen the player

**Expected behavior**
Player starts without playing audio.

**What actually happens**

The last song will start playing (from the song beginning) for a short moment before the player stops it.
When the song stops the "Pause" button switches back to the "Play" button, so the playing state is reflected in the UI.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: Version 99.0.4844.51 (Official Build) (64-bit)

**Comment by fapdash** [comment]
Both, sound is playing, which is also reflected in the UI.

**Comment by YehudaKremer** [comment]
Hello

For me, the player open in "play" status and it take a slip second to switch to "pause",
but on my pc i don't get any sound (maybe my pc is faster so i don't hear the sound).

i think i fix it in [v0.2.1-hotfix1](https://github.com/harmonoid/harmonoid/tree/v0.2.1-hotfix1), @fapdash can you please try this version
