### ISSUE TITLE
Hello, how can I implement System Media Transport Controls in Flutter?

### ISSUE THREAD

**Issue by itning** [harmonoid/harmonoid#244]
Is there any library I can use?

like this :

![image](https://user-images.githubusercontent.com/19759891/160238437-56357282-9c43-4ede-a8be-8c1452f70ba9.png)

**Comment by mytja** [comment]
Harmonoid uses [smtc-win32](https://github.com/harmonoid/smtc-win32), which is a propriatery package and is not open-source. You can however use it if you are supporting Harmonoid through Patreon (have a look at README)

Alternative is [libwinmedia](https://github.com/harmonoid/libwinmedia), which is unmaintained and at some parts not written well.

**Comment by itning** [comment]
All right,Thanks,
By the way, Do you currently have plans to write a flutter plugin to implement System Media Transport Controls ?

**Comment by mytja** [comment]
- We've already written packages/plugins with System Media Transport Control (SMTC) - it's called `smtc-win32` and is propriatery. You can only use it if you are Harmonoid supporter on Patreon.
- `libwinmedia` is also using SMTC, but is deprecated.

Pick one of above if you want to use SMTC. I cannot help you more.

**Comment by itning** [comment]
OK, Thanks.
