### ISSUE TITLE
download songs

### ISSUE THREAD

**Issue by venkat2305** [harmonoid/harmonoid#249]
can you add an option to download songs with meta data and time synced lyrics.
thank you.

**Comment by alexmercerind** [comment]
Sorry, I mis-read the question. I'm not going to add download feature.

**Comment by venkat2305** [comment]
ok then , as you are planning to add time synced lyrics , can you given an option which shows the lyrics with time stamps?

**Comment by alexmercerind** [comment]
> ok then , as you are planning to add time synced lyrics , can you given an option which shows the lyrics with time stamps? like this [00:30.02]line 1 [00:31.26]line 2 [00:32.77]line 3
> 

Yes I'll add time-synced lyrics & you'll love it. README has a section of "upcoming features".

**Comment by alexmercerind** [comment]
_work-in-progress [not-yet-released]_

> ok then , as you are planning to add time synced lyrics , can you given an option which shows the lyrics with time stamps? like this [00:30.02]line 1 [00:31.26]line 2 [00:32.77]line 3

https://user-images.githubusercontent.com/28951144/168900648-8f062e6d-a2f8-46b6-a55e-2054befbad58.mp4

> also many indian regional songs dont support lyrics, can you look into this as well?

![Screenshot 2022-05-18 013726](https://user-images.githubusercontent.com/28951144/168900809-7ac4e7bf-2483-4fb7-a084-8e5c9488bb10.png)
