### ISSUE TITLE
RAM instability issue in windows 

### ISSUE THREAD

**Issue by Vickykarthi32** [harmonoid/harmonoid#255]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. v0.2.1]

**Smartphone (please complete the following information):**
 - Version [e.g. v0.2.1]

**Comment by alexmercerind** [comment]
RAM usage highly depends upon the content you're visiting. I've noticed RAM to be as high as 200 MB and as low as 60 MB. A large number of images being displayed on the screen corresponds to higher CPU usage & it dips down again as you navigate. Still, I won't call anything below 300 MB poor, considering we don't look that uneasy on eyes.
We have a note mentioning this in the project's README at https://github.com/harmonoid/harmonoid#limitations.

Hoping to get next release ready soon with stuff.
