### ISSUE TITLE
Updated French translation for 0.2.2 release

### ISSUE THREAD

**Issue by ejacquemoud** [harmonoid/harmonoid#257]
Hello,

please find below the French translation JSON file updated for 0.2.2 release:
https://1drv.ms/u/s!Aqw96PLzHRKEifQoyysB_Fnqhb2V5Q?e=nuCyBN

Regards,
Etienne J.

**Comment by alexmercerind** [comment]
Apologies for the delay. I kept forgetting to commit these translations. Appreciate your work & time.
