### ISSUE TITLE
infinite loading

### ISSUE THREAD

**Issue by Luiz-bro** [harmonoid/harmonoid#258]
**Describe the bug**
When trying to add the songs, the application keeps loading infinitely, I've tried to change the directory through the configuration file but without success

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_20220427-103139](https://user-images.githubusercontent.com/67080890/165530448-d50a6d7c-dae3-45dd-8721-1b75c42a9e45.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. motoe5]
 - OS: [e.g. Android 8.0]
 - Version [e.g. v0.2.2]

**Comment by alexmercerind** [comment]
Hi! Thanks for the report. We're trying to figure out solution to this on Android.
This is first Android variant & has this problem in it.
I'll let you know.

**Comment by alexmercerind** [comment]
Hello @Luiz-bro,

May you please try out: https://github.com/harmonoid/harmonoid/releases/download/v0.2.2/harmonoid-android.apk.

I hope this won't cause infinite loading. Also, please check that metadata is correctly fetched.
Thanks.

**Comment by alexmercerind** [comment]
Someone at Discord has confirmed the working of the fix. Closing.

Feel free to re-open or comment if anyone can still reproduce.

**Comment by Luiz-bro** [comment]
Thanks a lot for the fix it worked perfectly

**Comment by Luiz-bro** [comment]
Does the app support playing flac files?

**Comment by Luiz-bro** [comment]
I tried to play a song in this format but I was not successful the audio just doesn't come out

**Comment by alexmercerind** [comment]
> Does the app support playing flac files?

In theory, yes. It should play any format flawlessly.
If you're sure that file is playable but not playing inside Harmonoid, then you may mail me a sample at alexmercerind@gmail.com or attach here.
Thanks.
