### ISSUE TITLE
YTM save artists/albums in library

### ISSUE THREAD

**Issue by hornyjailfish** [harmonoid/harmonoid#260]
I use harmonoid as youtube music player and local collection became rudiment feature in this case
Follow artists and add albums from ytm will be nice addition for users like me

It's definitely must be optional because people dont want mess online and local music (I think)
Possible feature with it: notify/recommend new music from artists in library

**Comment by alexmercerind** [comment]
Noted. I actually had this in mind. Ability to "pin" favorite albums & artists from YTM.

**Comment by alexmercerind** [comment]
No longer planning to invest time into this.
