### ISSUE TITLE
Pitch adjustment

### ISSUE THREAD

**Issue by Bryceed** [harmonoid/harmonoid#266]
**Actually it's possible to change the speed, but not the pitch itself.**

Changing the pitch can be useful to avoid copyright problems (ex. recording/streaming/share) in some platforms, and fun for those who likes nightcore/daycore versions (and it is, basically, the pitch adjustment for the same regular song).

**Comment by alexmercerind** [comment]
Accepting as a feature-request. Expect it to land in next stable release.
Shifting pitch of the music can surely be an enjoyable experience for some.

Thanks.

**Comment by alexmercerind** [comment]
Added!
https://github.com/harmonoid/harmonoid/releases/tag/v0.2.5

![](https://user-images.githubusercontent.com/28951144/173228896-9a14aa06-7d65-43f2-977e-824b65eb14de.png)
