### ISSUE TITLE
Translation History and Liked Songs

### ISSUE THREAD

**Issue by maisondasilva** [harmonoid/harmonoid#273]
These two variables could not find the translation file.

![image](https://user-images.githubusercontent.com/11423362/168453662-4da6f28c-5de5-41ef-91dc-315a71fdb48a.png)

**Comment by maisondasilva** [comment]
Problem is fix in new translation @alexmercerind

**Comment by alexmercerind** [comment]
> Problem is fix in new translation @alexmercerind

Yes!!!

**Comment by alexmercerind** [comment]
Thankyou very much!
