### ISSUE TITLE
Local Lyrics

### ISSUE THREAD

**Issue by kou9221** [harmonoid/harmonoid#282]
Question: Is this music player supports a .lrc file for local music manually or downloaded from somewhere in the internet?

**Comment by alexmercerind** [comment]
Loading a `.lrc` file is a valid request, but I don't have much time to invest in this project these days.
Keeping the issue opened.

For the lyrics, we are working on this in the next release:

![](https://github.com/harmonoid/harmonoid/blob/dc0ad2f62bff20cb013f72dccd118a9108d9ebb8/visual.gif?raw=true)

&

https://cdn.discordapp.com/attachments/809529583622946876/976209962369966100/preview_preview.mp4

<hr></hr>

Next in list:

- [x] Time-synced lyrics.
- [x] Visuals.
- [x] Pitch shifting.
- [x] Patches to `libmpv` bindings.
- [x] Refactored indexing based on `HashSet`.
- [x] In-app hyperlinks for local music collection.
- [ ] Bundling visuals.
- [x] Improved Discord RPC with album art & remaining time.
- [ ] Details editor screen.
- [ ] Ability to reorder now-playing-list.
- [ ] Above features on Android & other things that've been missed over time. Android version is terrible right now.

**Comment by kou9221** [comment]
> Loading a `.lrc` file is a valid request, but I don't have much time to invest in this project these days (and not much motivation either).
> Keeping the issue opened.
> 
> For the lyrics, we are working on this in the next release:
> 
> ![](https://github.com/harmonoid/harmonoid/blob/dc0ad2f62bff20cb013f72dccd118a9108d9ebb8/visual.gif?raw=true)
> 
> &
> 
> https://cdn.discordapp.com/attachments/809529583622946876/976209962369966100/preview_preview.mp4
> 
> <hr></hr>
> 
> Next in list:
> 
> - [x] Time-synced lyrics.
> - [x] Visuals.
> - [x] Pitch shifting.
> - [x] Patches to `libmpv` bindings.
> - [x] Refactored indexing based on `HashSet`.
> - [x] In-app hyperlinks for local music collection.
> - [ ] Bundling visuals.
> - [x] Improved Discord RPC with album art & remaining time.
> - [ ] Details editor screen.
> - [ ] Ability to reorder now-playing-list.
> - [ ] Above features on Android & other things that've been missed over time. Android version is terrible right now.

I see. Time-synced lyrics and visuals is soothing for me as i use them currently on my music player on android

Anyways thanks for your fast reply! I hope that this project improves more in the near future and support more for android version. Also nice app i really appreciate your work :)

**Comment by alexmercerind** [comment]
@kou9221 keeping the isssue opened until Android version is matched with feature-parity & a section is added to load "local lyrics".

**Comment by kou9221** [comment]
> @kou9221 keeping the isssue opened until Android version is matched with feature-parity & a section is added to load "local lyrics".

Alright my bad😄

**Comment by lars-goeran** [comment]
Sorry if I'm asking here. But what is needed to enable the synchronized lyrics?  I've tried a few things already. A .lrc file with the same name besides the mp3 or flac. And also the lyrics as internal id3 or flac tag. But the text never shows up on the "Now Playing Screen".

**Comment by alexmercerind** [comment]
> Sorry if I'm asking here. But what is needed to enable the synchronized lyrics? I've tried a few things already. A .lrc file with the same name besides the mp3 or flac. And also the lyrics as internal id3 or flac tag. But the text never shows up on the "Now Playing Screen".

Hi @lars-goeran! In current version, the app has no feature to read `.LRC` files, the app automatically looks for lyrics on the internet. Basically, if your music is correctly tagged, there are good chances you'll find lyrics.

From next version however (our next feature update will be out in a couple of days likely), you'll be able to select a `.LRC` file for a particular file/song.

Thanks!

**Comment by alexmercerind** [comment]
@lars-goeran & @kou9221,

[v0.2.9](https://github.com/harmonoid/harmonoid/releases/tag/v0.2.9) has been released. Now you can:
- Save `.LRC` file for a particular song by right-clicking the song on desktop or long pressing on mobile,
- Save `.LRC` file in the same folder to load it automatically (with same name as audio file).

**Comment by lars-goeran** [comment]
@alexmercerind Thanks for the new release! But unfortunately I have another problem with it. I have created an issues already for it.

**Comment by alexmercerind** [comment]
> @alexmercerind Thanks for the new release! But unfortunately I have another problem with it. I have created an issues already for it.

Let's have conversation about it on that thread.
