### ISSUE TITLE
Player considering last song as the first item of indexed list

### ISSUE THREAD

**Issue by Bryceed** [harmonoid/harmonoid#283]
**Describe the bug**
When you start the player for the first time, the first song/playlist works as expected (same audio for the same title), but when you try to change the song, occurs a bug that switch the audio from the displayed song, playing the last audio with the actual title - and the actual expected music when the player changes for the next song title.

**To Reproduce**
1. Play any song (single or playlist)
2. Switch from another song out of actual playlist

**Expected behavior**
The audio always should correspond with the same title.

**Screenshots**

https://user-images.githubusercontent.com/42657376/173237601-473dc604-2b0e-457f-8739-1fb73f1f1cec.mp4

*_issue on 0:20 and above_

**Desktop (please complete the following information):**
 - OS: Linux Mint (Ubuntu-based distro)
 - Version: 20.4 - Cinnamon

**Comment by alexmercerind** [comment]
Hi @Bryceed, 
I recall I recently patched this issue in one of the releases recently. Could you please - make sure that you're on the latest version?

Thanks.

**Comment by Bryceed** [comment]
Hi, @alexmercerind!

You're talking about the `v0.2.4` or from some PR not released yet? Because it's already in the last available version.
![image](https://user-images.githubusercontent.com/42657376/173238336-35f8ec46-feb4-4f56-89d9-12e67615e95d.png)

Thanks!

**Comment by alexmercerind** [comment]
https://github.com/harmonoid/harmonoid/releases/tag/v0.2.5

Addressed in latest release.
