### ISSUE TITLE
Here are some issues/suggestions, looking forward to its development 😆

### ISSUE THREAD

**Issue by SiddharthSharma16923** [harmonoid/harmonoid#284]
1. my wifi connection , went unstable for a min , the playback stops , the app shall be easily able to precache the whole music file (its literally 4 mb stream) ,
2. and disk caching is not a thing , wish to see that in future (popcorn time was so awesome, bcz it can play , at the same time ,the file is saved to disk )
3. search box : cant use backspace at all , typing adds to the previous string :( ,fixed by relaunch
had opened too many search results
5. sometimes, there are 0 results , if i give in a typo
6. the Yt music , button needs to be on the surface (not hidden under the 3 dots menu)
7. the app icon , it needs improvement , or add some contrast to it , bcz i cant tell if its a just a hdd icon or a music box 
8. add a download button (tho this wont be nedded if we follow the popcorntime like approach , just cache dem all , delete the older caches , let the user set a limit to how much space is to be used for caching )
9. the speed change button needs + and - buttons , its not so intuitive to use a tiny slider with a mouse
10. the default volume on launch , why is it 50%? , or is it 100% , with space for 200% boost? , idk , this is not really a issue
11. exporting history , to a text file (format can be , title + artist + video uploader if artist missing)
no need to rush, this app is perfectly usable , right now , does what it needs to🙂
*lol , sorry i asked too much.

a random song : "madcon beggin instrumental"

**Comment by alexmercerind** [comment]
Hey! A lot of these issues are already addressed in next release (a huge one), and few are ones that I can't fix.

Will let you know soon, thanks for the feedback.

**Comment by alexmercerind** [comment]
> my wifi connection , went unstable for a min , the playback stops , the app shall be easily able to precache the whole music file (its literally 4 mb stream)

Wanted to reply to this issue in particular,

I had disabled all kinds of caching in previous versions to aggressively decrease RAM usage (reduced demuxer cache to bare minimum). However that doesn't result in good experience, late realised. In next releases, caching will be back on track.

**Comment by alexmercerind** [comment]
Most of the things are addressed in the latest version: https://github.com/harmonoid/harmonoid/releases/tag/v0.2.5 (scroll down for download links). Remaining is something we'll think upon or can't be addressed.

<hr></hr>

![](https://github.com/harmonoid/harmonoid/blob/assets/harmonoid_W8Oi1qPZ0O.webp?raw=true)
![](https://github.com/harmonoid/harmonoid/blob/assets/harmonoid_zZZ1d0yO5G.webp?raw=true)
