### ISSUE TITLE
Import from yt music error

### ISSUE THREAD

**Issue by tbm98** [harmonoid/harmonoid#293]
**Describe the bug**
import from yt music say internet problem but work fine if turn on 1.1.1.1 (warp).
although show internet error but playlist name still work correct.
playlist: [here](https://www.youtube.com/playlist?list=PLiLhVQdXFJSgyDBUKqv9N1W4LSjFDWgFg)
![Screenshot 2022-07-15 214356](https://user-images.githubusercontent.com/52562340/179247272-3bfd5963-f199-4707-8ef4-4152eea40553.png)

**To Reproduce**
1. Go to playlist
2. Click on import from yt music link: https://www.youtube.com/playlist?list=PLiLhVQdXFJSgyDBUKqv9N1W4LSjFDWgFg
3. show internet error
4. turn on 1.1.1.1 and try again
5. work fine

**Expected behavior**
still work when turn off 1.1.1.1.

**Screenshots**
![Screenshot 2022-07-15 214356](https://user-images.githubusercontent.com/52562340/179247875-ecfc33eb-2b9e-4862-863d-749c76bd3aa9.png)
.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version v0.2.5

**Comment by alexmercerind** [comment]
I can import it.

**Comment by alexmercerind** [comment]
You can try this though: https://github.com/harmonoid/harmonoid/issues/155#issuecomment-1099983134.

**Comment by tbm98** [comment]
Oh yes. YT music not available in my country. Thank you
