### ISSUE TITLE
For Android when?

### ISSUE THREAD

**Issue by MrConqueror** [harmonoid/harmonoid#294]
**Describe the new feature you'd like**

You may add images for extended description.

**Comment by alexmercerind** [comment]
Android already has many good looking music players, use them not this.

Windows & Linux didn't have much going on. Everything there looks old or has wierd UI. I'm currently just targetting desktop, it still needs more features.

I'm not giving any date for Android, I don't like half baked or bad looking inconsistent UIs. This is a hobby project without any big funding, so don't expect any swiftness.
