### ISSUE TITLE
Custom visuals bug

### ISSUE THREAD

**Issue by kou9221** [harmonoid/harmonoid#297]
**Describe the bug**
When closing the app and opening it again after some time the custom visuals background resets to only any available default

**To Reproduce**
1. Open harmonoid
2. Go to its settings and add a custom visuals
3. Close the app and open it again
4. Go to settings or now playing screen to check if the custom visuals persist

**Expected behavior**
Should always stay even after closing the app

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: v0.2.5

**Actual Recording**

https://user-images.githubusercontent.com/98811570/179449905-cd3cf0fc-b272-4711-a67c-a5e6e4d32c5b.mp4

**Comment by alexmercerind** [comment]
Whoops! Thanks for the report.

**Comment by alexmercerind** [comment]
This has been addressed in the latest version. Please download the new version.

Thanks! Have a good one.
