### ISSUE TITLE
Spanish language support

### ISSUE THREAD

**Issue by fabriguzden** [harmonoid/harmonoid#299]
It would be nice if they added support for the Spanish language

**Comment by alexmercerind** [comment]
"they"?
It's not my responsibility to translate. Spend your time & submit the translation.

I'm a developer & don't get time to translate even my own mother tongue in this project.

https://github.com/harmonoid/harmonoid/blob/master/assets/translations/en_US.json

**Comment by fabriguzden** [comment]
ok, i understand, sorry

**Comment by fabriguzden** [comment]
I'm going to do it in a few days
