### ISSUE TITLE
bad search , cant search a channel/artist + now playing ui need a indicator button , channel name shall be clickable

### ISSUE THREAD

**Issue by SiddharthSharma16923** [harmonoid/harmonoid#301]
situation: long ago ( around 5 years), there was a song/instrumental(i dont even clearly remember) from the channel , spinnin' records 
the only thing i remember about it is that it was a groovy bassline and it was my fav at that time , i kinda remember its thumbnail , but i am unable to find it (this channel uploads so much video , such a mess) 

now for this purpose
it would be super nice to have these features
1. a working search (i cant find , the spinnin' records channel at all , i cant get to the channel page in the app , the search results are seriously dumb , i am angry , pls try it yourself , you will be "amazed"
- a very easy approach to this is , to simply make the channel name clickable , or let me enter the user id of the cannel in the search or let me enter the literall channel url "https://www.youtube.com/channel/UCpDJl2EmP7Oh90Vylx0dZtA" in the search bar
2. youtube does provide audio only stream at multiple quality ( can be seen on any https://invidious.io/ frontend)   so for the purpose this situation (as mentioned on top) , i would like to skim through a lot , lot of music , and unlike elon musk , i have to pay for my internet , so i would really appreceate if you could provide a setting that plays audio at the `lowest possible aka , worst quality audio`
3. oh i just remembered one more suggestion: 
- the "now playing screen" , i have turned it off from settings to open automatically , 
- it is impossible for a noob(literally what happend with me) to find how to get into the now playing ui ( i was trying to see if i can click on the channel's name "spinnin' records" , found out but i cant ) , its at bottom left , there shall be a icon to indicate it

**Comment by SiddharthSharma16923** [comment]
- **NSFW** content below warning!

<details>
  <summary>some extra stuff i wrote , but decided to not post it as part of the above issue  as it is </summary>
  
  
  
i actually decided it in 2020 , to find that music video , i failed at that time , i also lacked time , today i had time , so i set out on it , , but i again failed ( i tried my best , i went to https://inv.vern.cc/channel/UCpDJl2EmP7Oh90Vylx0dZtA?page=52
explored 52 pages on it , and listened to many audios 
but i failed :( , i thaught that the harmonoid app would be usefull at this scenario"
and i am still in pain , my ears still ache , and await to be soothened by that melodious funky bass-line (lol kdrama level acting skills here, xD xD)

youtube UI is a pain , i am at the brain transplant hospital right now , my previous brain is overused and all the braincells died 
while trying to browse the slow youtube ui

:( , sadly , .... , you did wrong to me my friend
but i will forgive you
bcz my heart is too big 
idk ,the doctor said it its way to big , "bruh do some exercise , your koreandrama jugs bigger than my wife" 

note from the doctor:  the patient is probably not gonna be saved , he is in too much comma(,,,,,,,,) , 
`and he might not wake up untill the next release of harmonoid 😥 `
all these words written above are copied from his big juggs , he wrote it all on his body, like ghajni(try ,google ghajni here image 
![image](https://user-images.githubusercontent.com/75392515/180657919-4318790a-e6bc-40bc-ac6a-e39f1f89b265.png)
) , before the operation ,the naughty nurse got jealous of the big milkers of a man , and tried to destroy them !
she is eviL !!!! ,we tried our best to recover him , but all the words and sentences got scambeled , so pls pay scrunity while you read , as the text might be mis structured, at the end we had to attach cow's jugs to the man , to fill in the space for the lost skin which the EVIL NURSE ate , saying that , this will help her , grow her flatboard  ![image](https://user-images.githubusercontent.com/75392515/180655883-5dae8053-1acb-4ca1-b1c3-249a6305b590.png) well techniccally the surface area of the body is increased so as a bonus he has improved cooling of his human body , along with the benefit of free milk supply , anywhere , anytime 

</details>

**Comment by alexmercerind** [comment]
Currently, search results in YouTube Music section, are EXACTLY SAME as YouTube Music.
There's very little I can do.

- I'm (personally) happy with search results (because they're exactly same as YouTube Music). ¯\_(ツ)_/¯ The only issues in the existence related to current YouTube Music are:
- #275. See last comment.
- #143. This is a big one. If I ever work on this, it is going to have like/dislike, history sync support. This is also a bit of non-goal as of now.
- Hyperlinks. Possibly I will never implement. This is a non-goal.
- We can never be equivalent to official frontend written by employed engineers at Google. And most importantly, YouTube Music isn't primary feature of Harmonoid.
- The only qualities available on free YouTube Music are M4A ~140 kbps & OPUS ~250 kbps. Application automatically chooses best one, if it is available. There is no major "choice" & won't make a difference eitherway. 
- `Spininn' Records` is NOT A GODDAMN artist. It's a channel. Do you search for a YouTube channel on Spotify or any music service? No you don't.

> the "now playing screen" , i have turned it off from settings to open automatically.

Me as-well :)

> it is impossible for a noob(literally what happend with me) to find how to get into the now playing ui ( i was trying to see if i can click on the channel's name "spinnin' records" , found out but i cant ) , its at bottom left , there shall be a icon to indicate it

Not my job. Feel free to maintain a documentation/user-guide for the UI/features we've implemented so far.

**Comment by alexmercerind** [comment]
Either way, I don't have so much time & power to do it & neither anyone else will have.
I will try best to improve existing situation, subscribe to listed issues for any news.

This is just a hobby project, surviving on free-time & voluntary donation from people for keeping me motivated.
