### ISSUE TITLE
External app deps not existing anymore

### ISSUE THREAD

**Issue by iBog** [harmonoid/harmonoid#306]
no such repos from https://github.com/harmonoid/harmonoid/blob/master/.gitmodules:

[submodule "external/libmpv.dart"]
	path = external/libmpv.dart
	url = https://github.com/harmonoid/libmpv.dart.git
[submodule "external/smtc-win32"]
	path = external/smtc-win32
	url = https://github.com/harmonoid/smtc-win32.git
[submodule "external/harmonoid_visual_assets"]
	path = external/harmonoid_visual_assets
	url = https://github.com/harmonoid/harmonoid_visual_assets
[submodule "external/mpris_service.dart"]
	path = external/mpris_service.dart
	url = https://github.com/harmonoid/mpris_service.dart.git
[submodule "external/ytm_client.dart"]
	path = external/ytm_client.dart
	url = https://github.com/harmonoid/ytm_client.dart
[submodule "external/safe_session_storage"]
	path = external/safe_session_storage
	url = https://github.com/harmonoid/safe_s

**Comment by alexmercerind** [comment]
Please refer to https://harmonoid.com.

Thanks!
