### ISSUE TITLE
Unable to build due to external plugins related error

### ISSUE THREAD

**Issue by sunildhiman90** [harmonoid/harmonoid#310]
I am getting this error while trying to run flutter pub get

Could not find a file named "pubspec.yaml" in "F:\AndroidStudioProjects\Kotlin\flutter_music_player\external\safe_session_storage".
pub get failed (66; Could not find a file named "pubspec.yaml" in "F:\AndroidStudioProjects\Kotlin\flutter_music_player\external\safe_session_storage".)

Unable to build and run
![image](https://user-images.githubusercontent.com/35147222/183239380-efd27877-20c4-43ba-9c5b-a0b272e82f25.png)

**Comment by alexmercerind** [comment]
![image](https://user-images.githubusercontent.com/28951144/183243530-5233a319-d49e-4d00-8f13-b5b556762890.png)

![Screenshot 2022-08-06 150947](https://user-images.githubusercontent.com/28951144/183243608-bfe319d0-5ef8-4c7a-acec-b58b95b502cb.png)


There is it.
