### ISSUE TITLE
Racist Lyrics And No Way to Stop Displaying Them

### ISSUE THREAD

**Issue by Kandelai** [harmonoid/harmonoid#313]
**Describe the bug**
Was playing a track from the new Elvis Movie Soundtrack entitled 'Trouble' and the most, vile racist lyrics appeared, obviously not the lyrics for the track. I tried to go into settings to see if I could shut them off, but doesn't seem to be an option. I am sure someone hijacked the lyrics from whatever source you are pulling from, but there should be an option included to turn off lyrics. You might also want to find a new lyrics source.

**To Reproduce**
1. Use the Youtube Music Option and search for 'ELVIS (Original Motion Picture Soundtrack)'
2. Select the track called 'Trouble' and feast your eyes on some racist lyrics.

**Expected behavior**
Not to see racist lyrics and to have an option to stop showing them.
**Screenshots**
Screenshot included.

**Desktop (please complete the following information):**
 Operating System: Garuda Linux
KDE Plasma Version: 5.25.4
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.18.16-zen1-1-zen (64-bit)
Graphics Platform: X11

**Comment by alexmercerind** [comment]
There is an option to turn off lyrics.
Press that "A" button.

**Comment by alexmercerind** [comment]
I will find correct lyrics & set an exception rule.

**Comment by alexmercerind** [comment]
It should show the correct lyrics now.
This button hides the lyrics:

![](https://user-images.githubusercontent.com/28951144/184544622-c9cd7e13-749b-4c3f-ae15-8e0fb022dad0.png)

Project needs a documentation as even more features are coming with time, but there is no way I'll be able to write those.

Thanks for using Harmonoid!
