### ISSUE TITLE
[Bug] Played Previous Song when changing song and repeat is on

### ISSUE THREAD

**Issue by floirelle** [harmonoid/harmonoid#314]
**Describe the bug**
When i play a song, and decided to change the song, it keeps playing the previous one, and i have to click next to play the new song (but the screen also change to another song in queue, so basically it's always 1 song behind)

**To Reproduce**
1. Play a song from youtube music
2. Play a new song from youtube music
3. It plays the first song

**Expected behavior**
When playing a new song, should change song to new song

**Screenshots**
![image](https://user-images.githubusercontent.com/33004872/186610589-926d83f5-ee55-49b5-b98c-1af827914618.png)
Should play Someone like you, instead it plays Hello

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version: 20.04.4 LTS

**Comment by alexmercerind** [comment]
mpv version?

**Comment by floirelle** [comment]
running `apt list mpv libmpv-dev` gives this ouput (should be newest version)
libmpv-dev/focal,now 0.32.0-1ubuntu1 amd64 [installed]
mpv/focal,now 0.32.0-1ubuntu1 amd64 [installed]

**Comment by floirelle** [comment]
sorry, missclicked the button

**Comment by alexmercerind** [comment]
> sorry, missclicked the button

thanks for the info! the compatibility with `mpv` versions lower than v0.33.0 will be added with upcoming version. our next feature update will be out in a few days.

**Comment by alexmercerind** [comment]
Hi @floirelle,

[v0.2.9](https://github.com/harmonoid/harmonoid/releases/tag/v0.2.9) has been released. Now mpv versions lower or equal to v0.32.x work correctly.
