### ISSUE TITLE
No download links :(

### ISSUE THREAD

**Issue by thenoobtester** [harmonoid/harmonoid#319]
**Describe the bug**
I went on https://harmonoid.com/ as suggested to download the app, the went on the download page https://harmonoid.com/downloads/ but all links point to https://harmonoid.com/downloads/#.

Could you please give me a link to download for Debian? Thank you for this piece of software which seems really neat.

**Comment by alexmercerind** [comment]
You need to have JavaScript enabled & just click on "Ubuntu / Debian [.deb]" on the [download page](https://harmonoid.com/downloads).

You may use [this link](https://github.com/alexmercerind2/harmonoid-releases/releases/download/v0.2.8/harmonoid-linux-x86_64.deb
) for downloading the `.deb` directly.

<hr>

Also, please note that a major update is about to be released in a day or two, which will bring many new features, performance improvements (especially Linux) & crucial fixes.

**Comment by thenoobtester** [comment]
Thank you for your help. 

Sorry i had a popup blocker which caused the issue.
