### ISSUE TITLE
language, mix & invalid

### ISSUE THREAD

**Issue by Feelogil** [harmonoid/harmonoid#323]
### [ver:0.3.0](https://github.com/harmonoid/harmonoid/releases/tag/v0.3.0)

> invalid

- Russian
- Svenska

Russian translation from 09.02.2022 worked on [ver:0.2.9](https://github.com/harmonoid/harmonoid/releases/tag/v0.2.9)

https://user-images.githubusercontent.com/61083015/188306751-57998c3c-8a20-40a8-9140-96161992e18a.mp4

p.s. ru_RU.json checked, no errors. maybe missed....

**Comment by alexmercerind** [comment]
Hi @Feelogil, I noticed the problem few minutes after publishing :sweat_smile:.

I have updated the same version with the fix. Thank you very much!

Download: [v0.3.0](https://harmonoid.com/downloads).
