### ISSUE TITLE
Add Android Material You icon

### ISSUE THREAD

**Issue by Darkempire78** [harmonoid/harmonoid#324]
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

Since android 13, icons should follow Material You. This is very simple to do

**Comment by alexmercerind** [comment]
> Since android 13, icons should follow Material You. This is very simple to do.

Thank-you for the link. We do have an adaptive icon, but monochrome variant is currently missing.

Currently Material You implementation is pending. As discussed in notes of [v0.2.9](https://github.com/harmonoid/harmonoid/releases/tag/v0.2.9).

Presently, app very (very) strictly follows Material 2 spec at material.io.
I will add optional toggle to switch between two iterations of Material Design.

Thanks!

**Comment by alexmercerind** [comment]
Added in v0.3.1.
