### ISSUE TITLE
Opus metadata not read

### ISSUE THREAD

**Issue by thenoobtester** [harmonoid/harmonoid#327]
**Describe the bug**
I have this opus file downloaded with yt-dlp and it's metadata is not read by Harmonoid. When I have yt-dlp convert it to mp3 it does work though.

**To Reproduce**
Here is the command line I used to download it:

`yt-dlp -f 'ba' -x --audio-format opus --add-metadata --embed-thumbnail "https://music.youtube.com/watch?v=[Removed ID]" -o '%(title)s_[%(id)s].%(ext)s'`

**Expected behavior**
The metadata should appear in Harmonoid (title, author, cover art)

**Desktop (please complete the following information):**
 - OS: Debian 9
 - Version 3.0 (tested too with 2.9)

**Comment by thenoobtester** [comment]
Thank yo ufor the reply. I ran the command again and it worked on my computer so i don't know what to day about that. However here is the file it it helps `https://www106.zippyshare.com/v/FctvVTYa/file.html`

The command on my computer saves the file with a .opus extension.  Is webm supported by Harmonoid? I tried once and it didn't index my webm files.

**Comment by thenoobtester** [comment]
I tried again with an ogg file with this command (pretty much the same as earlier):

`yt-dlp -f 'ba' -x --audio-format vorbis --audio-quality 0 --add-metadata --embed-thumbnail "https://music.youtube.com/watch?v=ID" -o '%(title)s_[%(id)s].%(ext)s'`

and it doesn't read the metadata either, it only works when I choose mp3.

**Comment by alexmercerind** [comment]
Hi @thenoobtester, the provided sample shows metadata tags & album correctly inside Harmonoid.

The primary issue is that your `mpv` version on your system is likely below v0.32.x. v0.33.x+ shows opus tags correctly.

You should upgrade your mpv using some external PPA, considering Debian is not very good in regards of updates.


![](https://user-images.githubusercontent.com/28951144/188699363-d630c152-5750-43b3-b914-414313a232ab.jpg)

**Comment by thenoobtester** [comment]
Ok, thank you for your help. I will try to figure something out :)

**Comment by alexmercerind** [comment]
Few days ago, I was on elementaryOS with mpv v0.32.x & my music metadata was also not showing.

**Comment by thenoobtester** [comment]
Yeah, it's confusing because when I run mpv -v i get:

`[cplayer] mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects`

but when I play the file with : ` mpv New/Back\ To\ Black_\[rbBbQ-jldvQ\].opus ` 

It outputs this, which shows it reads the metadata well:
`(+) Video --vid=1 [P] (png 1280x720)
 (+) Audio --aid=1 --alang=eng 'Back To Black' (opus 2ch 48000Hz)
File tags:
 Artist: Amy Winehouse
 Album: Back To Black
 Comment: https://www.youtube.com/watch?v=rbBbQ-jldvQ
 Date: 20180726
 Title: Back To Black
Displaying attached picture. Use --no-audio-display to prevent this.
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 1280x720 rgb24
AV: 00:03:24 / 00:04:00 (84%) Cache: 36s/1MB`

**Comment by alexmercerind** [comment]
So, is mpv is reading the data & showing album art correctly, it should show fine inside Harmonoid too.
Sadly, I cannot bundle mpv on Linux within package, like it is on Windows.
You can try to re-index or open using file explorer into Harmonoid.

**Comment by alexmercerind** [comment]
Also, Harmonoid actually uses the shared library from `libmpv-dev` package & `mpv` is just their frontend.
