### ISSUE TITLE
[FEATURE] Misc Usability, Easier stream search, and easier share on mobile

### ISSUE THREAD

**Issue by Quackdoc** [harmonoid/harmonoid#335]
**Describe the new feature you'd like**
When searching for music it would be nice if there was a button to show "Stream" results directly from the search page. 

I love the app, My mother likes it too but finds the streaming to be a bit hard to remember so It would be nice if there was either a dedicated page on the homescreen on android and desktop, or if we could see a "Search streaming services" instead of a just a No results page and it would also be really nice if there was a clickable icon in the search bar. or some other way of doing it when search results do show up.

As for the second request, would it be possible to add the share button on mobile directly to the screen somewhere? so clicking the buttons is not necessary? she does like sharing music on facebook and over messenger etc. but she is not the most technologically literate person.

Thanks for the great app! I'm now using it on both desktop and mobile and loving it a lot.

**Comment by alexmercerind** [comment]
Thanks for the feedback & using Harmonoid! I'll work on the things once I'm able to spare my time.

One other thing I'd like to say is that YouTube Music streaming feature is something I have implemented, but isn't seen as the _primary_ feature of the app. You never know what Google may decide about this. In any unfortunate case like that, I will have to remove it.

Playback & management of local music & building a nice, cohesive & fluid experience for it is the main goal.

Thanks!

**Comment by alexmercerind** [comment]
The local music library has been focus of the project for quite some time now. No longer considering any YouTube Music etc. related issues.
