### ISSUE TITLE
Long / double click to add album to queue.

### ISSUE THREAD

**Issue by wennaspeedy** [harmonoid/harmonoid#339]
I am missing to simplier adding album to queue. 

Now I have to open album --> click to play/queue --> click arrow to back. But it is soo annoying

**Comment by alexmercerind** [comment]
Hi @wennaspeedy, this is indeed missing for Android. 

For Windows/Linux, I have this button:

![harmonoid_vSZQA8FBvc](https://user-images.githubusercontent.com/28951144/194512804-ed8bfbcd-1e34-471b-8ac0-127ab5424afa.png)

**Comment by wennaspeedy** [comment]
Yes I know but I mean double/long click on album screen:

![image](https://user-images.githubusercontent.com/10447994/194514251-7aa039a1-1c2f-4ae1-b4f0-bbeaa34ee3c3.png)

**Comment by alexmercerind** [comment]
It can be done. No dates however.

**Comment by alexmercerind** [comment]
This is live with the new update: [v0.3.4 • Essentials](https://github.com/harmonoid/harmonoid/releases/tag/v0.3.4).

Feel free to share any regressions or issues. I hope this improves your music experience.
