### ISSUE TITLE
Disabling animation

### ISSUE THREAD

**Issue by wennaspeedy** [harmonoid/harmonoid#341]
It would be nice to disable/change transition animations. The animations are very slow...

**Comment by alexmercerind** [comment]
Implemented in latest snapshot. Now you can change speed of animations or disable them entirely.

https://github.com/harmonoid/snapshots/releases

**Comment by alexmercerind** [comment]
Part of [v0.3.6](https://github.com/harmonoid/harmonoid/releases/tag/v0.3.6). Thanks!
