### ISSUE TITLE
feature request: expose parameters which identify an album uniquely

### ISSUE THREAD

**Issue by eedeidk** [harmonoid/harmonoid#344]
**Describe the bug**

Multiple Album Entries in case of album artists being different

**To Reproduce**

1. Add the music folders etc
2. You have Music Album but Singer is different of certain songs
3. Click Album Tab
4. See Multiple Album Entries

**Expected behavior**

One Unique Album sorted from Audio Metadata Album Field; even if it contains different singer for different songs from the same album

**Screenshots**

![image](https://user-images.githubusercontent.com/59429783/195376415-dddda0e7-deeb-49f2-9332-bfb3b3b95072.png)
If you notice Adele's Album is single entry because she is mentioned as singer in all the contaning songs,
but the 96 or 7/27 (Deluxe) does have multiple entry as its singer metadata is contains different artists

**Platform**

- OS: Linux
- Version: Ubuntu 22.04 LTS

**App version**

Please confirm that you're on the latest version available.

- Version: v0.3.3

**Comment by alexmercerind** [comment]
Hi @eedeidk, thanks for the report.

Currently, this is the intended behavior, an album is uniquely identified based on 3 parameters:
- Album
- Album artist
- Year

This is sort of important because an album with a same name may exist from multiple artists (quite common infact).
However, keeping this open as a feature request.

Thanks!

**Comment by eedeidk** [comment]
I agree but in the mean time it would be nice if you let the user have a settings toggle to identify album by Name & Year only, like Rhythmbox. Hope you look into it. Thanks.

**Comment by MSOB7YY** [comment]
i use albums to make a collection for youtube videos based on channel name, preventing duplication in albums is extremely important in such cases (and i really want it xD)

**Comment by alexmercerind** [comment]
Thanks for the request folks!

I have implemented this ability to configure the album parameters separately in development branch.

Expect next update (with this feature) by the weekend. See you then!

More information about the roadmap & other features coming with the update may be found at #348.
