### ISSUE TITLE
High GPU usage while being in "lyrics screen"

### ISSUE THREAD

**Issue by isaacItz** [harmonoid/harmonoid#346]
### Specs:
- Windows version: Windows 11 version 21h2 compilation, 22000.978
- CPU: AMD Ryzen 5 5500u Vega 7 graphics card
- Graphics card driver version: 22.9.1
- Harmonoid version: 0.3.3.0 (latest)

### Problem Description:
The program is using 20% percent of the GPU usage in the "lyrics view" screen.
I thought the problem was the background image, that is being rendered in real time, but no, I changed it for a static image but the problem persisted.
The GPU consumption changes depending if I'm on the lyrics, playlist screen, alto the consumption differs if I have maximized or minimized the app.
 
I share some images with the evidence collected:

[maximized in playlist screen](https://drive.google.com/file/d/14mToSg5M86UCcx0e8I-0jq-RbxFuWNHV/view?usp=sharing)
[maximized in lyrics screen](https://drive.google.com/file/d/1ee1Ek6Y2p_k-v_iFIxK6jiSc6i-TlleX/view?usp=sharing)
[minimized lyrics screen](https://drive.google.com/file/d/1npGw9w8TMAXzYc5Cea90EH1AvNwfcZNg/view?usp=sharing)

It only goes down when I change the view to the albums or whatever of the menus of the app.

**Comment by alexmercerind** [comment]
Hi @isaacItz, it's expected. 

Harmonoid is very lightweight compared to today's electron.js world.

But I cannot defy the computer science. At the end, we're going to need system resources according to the content that is being rendered (and the lyrics screen is quite heavy).
Larger the rendering area, larger the pixel buffer & rendering time. Thus, the CPU/GPU usage.

I'm not saying the performance cannot be further improved, but considering  "fullscreen" means that Harmonoid is the sole app in focus, it's not really a big issue. System resources are meant to be used, but not abused e.g. stolen from other apps, wasted in form of a memory leak or unnecessarily allocated.

<hr>

**Noting my existing message from the project website:**

> Harmonoid is meant to be modern & these animations or pixel-by-pixel painted elements will definitely have some expense on your CPU/RAM. It's not going to consume as less memory as [imgui](https://github.com/ocornut/imgui), [WxWidgets](https://www.wxwidgets.org/) or vanilla [Qt](https://www.qt.io/), but definitely NOT even close to what [electron.js](https://electronjs.org/) consumes (which most cross-platform apps tend to use).
> With that being said, performance is going to be improved overtime. [Flutter](https://github.com/flutter/flutter) is really new to desktop & a lot of performance improvements/patches are being made with time.
