### ISSUE TITLE
How do we sort by artist of the album?

### ISSUE THREAD

**Issue by Jagounet** [harmonoid/harmonoid#347]
**Ask your question here**
Thanks !

**Comment by alexmercerind** [comment]
Hi @Jagounet!

There's this button (see red arrow in the image) which allows to sort albums based on album artists. It's labelled as "artists" but it is actually "album artists", a mistake from my side.

There's a list of all the album artists on the left side. You can click on those names for jumping directly to the requested album artist in the whole list on the right side.

![Screenshot 2022-10-15 115813](https://user-images.githubusercontent.com/28951144/195985385-3fd1076e-0521-493e-aa88-5b867d9d4442.jpg)


Thanks!

This feature is only available for Windows & Linux. Android is newly developed & under progress (although Windows & Linux versions are also really new when we compare to existing applications).

**Comment by Jagounet** [comment]
No sort Artist, but Album Artist ?

**Comment by alexmercerind** [comment]
Yes.

**Comment by alexmercerind** [comment]
I feel the question has been answered. Closing the issue.
Let me know if you had something else (or some other feature) in mind, that Harmonoid doesn't have yet.

Thanks!
