### ISSUE TITLE
Unable to change visual

### ISSUE THREAD

**Issue by playoff4157** [harmonoid/harmonoid#351]
**Describe the bug**

How do I change the visual during music playback?

**Screenshots**
![ezgif-5-be325a143d](https://user-images.githubusercontent.com/106423243/201487426-83d0f265-a543-4119-9a77-9934b2532763.gif)

**Platform (please complete the following information)**

- OS: Manjaro Linux

**App version**

- Version: v0.3.3

**Comment by alexmercerind** [comment]
Hi @playoff4157,

The buttons below (see arrow) may be used to switch the backgrounds. Audio sensitive visuals are also in plans & a WIP.

![](https://user-images.githubusercontent.com/28951144/201487922-4b905896-8294-4675-99e5-8d417959cf00.jpg)

Thanks! Feel free to re-open.

A new update with many fixes & improvements is on it's way. It should be out by the weekend.
