### ISSUE TITLE
YouTube playlist cannot be imported completely

### ISSUE THREAD

**Issue by haruma1115** [harmonoid/harmonoid#352]
Sorry, my English is not very good, because I have the problem described in the title, I can't import all the videos (songs) into Harmonoid when I import the Youtube playlist, so I would like to ask if there is a solution, thanks.

Such as the following clip
https://i.imgur.com/1Rmiyfx.mp4

**Comment by alexmercerind** [comment]
Thanks for the report. I will take a look.

**Comment by haruma1115** [comment]
> Thanks for the report. I will take a look.

Thank you for your help.

**Comment by Black-StellarSpectrum** [comment]
If you don't mind what was that other app that you are using with that play button?

**Comment by alexmercerind** [comment]
> If you don't mind what was that other app that you are using with that play button?

YouTube itself. 🙆‍♂️

**Comment by Black-StellarSpectrum** [comment]
> > If you don't mind what was that other app that you are using with that play button?
> 
> YouTube itself. 🙆‍♂️

Oh ok I was thinking it was new ui or an app for youtube music😅

**Comment by alexmercerind** [comment]
The local music library has been focus of the project for quite some time now. No longer considering any YouTube Music etc. related issues.
