### ISSUE TITLE
Play next button does not work since the update v0.3.4

### ISSUE THREAD

**Issue by FloRyuK0** [harmonoid/harmonoid#356]
**Describe the bug**

**To Reproduce**

1. play a song
2. Click on the "next" button

**Expected behavior**
the song go to the next song available

**Screenshots**
![image](https://user-images.githubusercontent.com/114009421/202875205-d02310f2-7c4b-42ca-8b4f-55e5daa3756c.png)

**Platform (please complete the following information)**
Windows 11 22H2

**App version**
v0.3.4
![image](https://user-images.githubusercontent.com/114009421/202875362-6da208c7-9861-4829-908a-8e432a6423f6.png)
Please confirm that you're on the latest version available.
I confirm that i downloaded the latest version on the website

Does the app collect logs that i can attach below ?

**Comment by alexmercerind** [comment]
Please refer to #353.

Thanks!
