### ISSUE TITLE
Metadata editor

### ISSUE THREAD

**Issue by LoppyDuck** [harmonoid/harmonoid#363]
Please add metadata editing options. I use musicbee it has great metadata editing options that really helps to organize my huge music library. I really like the Ui of harmonoid but metadata editing is a must for me, and I think I speak for a lot of people.

**Comment by alexmercerind** [comment]
Hi!

It seems I missed this issue. There's a duplicate at: [Tag editing support: #277](https://github.com/harmonoid/harmonoid/issues/277). You may subscribe to it for updates.

Unfortunately, I do not have the time & resources to complete this feature request _i.e. implementation, testing & ensuring stability for wide range of audio formats_.

As of now, Harmonoid focuses on music playback + library management & does it best. It offers a stable experience with decent number of features (e.g. synced lyrics, visuals, pitch shifting, volume boost, sorting & ordering options etc. etc.), consistent Material Design UI & rich animations. I don't want to widen the scope to tag-editing for now.

<hr> 

It's going to be a challenge without remux-ing (FFmpeg) the file, [taglib](https://github.com/taglib/taglib) offers API to edit tags, but separate one for each format. It'll be very tedious to implement an abstracted API to support all possible formats.

Best we can do is to provide an option within [Harmonoid](https://harmonoid.com) to open [Picard](https://picard.musicbrainz.org/) externally for tag-editing. It's a well-tested & stable application for tag-editing specifically.

Thanks!

**Comment by LoppyDuck** [comment]
> Hi!
> 
> It seems I missed this issue. There's a duplicate at: [Tag editing support: #277](https://github.com/harmonoid/harmonoid/issues/277). You may subscribe to it for updates.
> 
> Unfortunately, I do not have the time & resources to complete this feature request _i.e. implementation, testing & ensuring stability for wide range of audio formats_.
> 
> As of now, Harmonoid focuses on music playback + library management & does it best. It offers a stable experience with decent number of features (e.g. synced lyrics, visuals, pitch shifting, volume boost, sorting & ordering options etc. etc.), consistent Material Design UI & rich animations. I don't want to widen the scope to tag-editing for now.
> 
> It's going to be a challenge without remux-ing (FFmpeg) the file, [taglib](https://github.com/taglib/taglib) offers API to edit tags, but separate one for each format. It'll be very tedious to implement an abstracted API to support all possible formats.
> 
> Best we can do is to provide an option within [Harmonoid](https://harmonoid.com) to open [Picard](https://picard.musicbrainz.org/) externally for tag-editing. It's a well-tested & stable application for tag-editing specifically.
> 
> Thanks!

Yeah that can also work
