### ISSUE TITLE
OPENING HYPERLINK FOR A SONG NOT IN THE LIBRARY

### ISSUE THREAD

**Issue by abiud254** [harmonoid/harmonoid#366]
When you open a music file that isn't in the Library from the file explorer with Harmonoid it plays fine. But the track is added to the History playlist. From there it plays fine but on pressing it's hyperlink, you get a white background and there's no way of getting out of it except from closing the app entirely.

1. Open a song that isn't part of a folder that you've already added into the app.
2. Click it's artist hyperlink
3. See error

**Expected behavior**
A white background which you have no way of getting out of is seen.

**Screenshots**

![Screenshot_20221217_013422](https://user-images.githubusercontent.com/66108188/208200439-6e368750-a827-4cd7-bc77-4921ee68a3e3.png)

**Platform (please complete the following information)**

- OS: Windows 
- Windows 11

**App version**
- Version: [e.g. v0.3.4]

**Comment by alexmercerind** [comment]
v0.3.5 is released. [Download latest version](https://harmonoid.com/).
