### ISSUE TITLE
track Context menu - command to delete file from disk

### ISSUE THREAD

**Issue by lucamosca1** [harmonoid/harmonoid#367]
Very useful when I want to 'clean' my playlist. I use Clementine only for this reason.

**Comment by alexmercerind** [comment]
???

![](https://user-images.githubusercontent.com/28951144/208419798-3103ad06-9152-4b87-a748-f91296e48947.jpg)

**Comment by alexmercerind** [comment]
On a serious note, am I missing something?

**Comment by lucamosca1** [comment]
Right my fault. But is better to differentiate delete from disk to delete from playlist.

**Comment by ybolu** [comment]
I wanted to remove some albums from Harmonoid, I right clicked on the albums and clicked delete. Soon I discovered the original files from disk were deleted. This was very disappointing.
It should be clear that it will delete the files from disk. A warning / confirmation is required.

p.s. nice looking, clean software. thanks.
