### ISSUE TITLE
Next and Previous buttons are not greyed out in view with the animation

### ISSUE THREAD

**Issue by pktiuk** [harmonoid/harmonoid#369]
**Describe the bug**
When I play a single song (empty playlist) and I am on a list/Album view `Next`, and `Previous` buttons are greyed out.
![obraz](https://user-images.githubusercontent.com/45544416/208758067-0aafd07b-9a47-472c-9686-9fced3ff3856.png)

But when I open view with visualization and lyrics they are not
![obraz](https://user-images.githubusercontent.com/45544416/208758395-91932767-de78-4407-ad3b-a41889ad14f1.png)

**To Reproduce**
1. Play any single song from Tracks list

**Desktop (please complete the following information):**
 - OS: Pop OS 22.04
 - Version v0.3.4

**Comment by alexmercerind** [comment]
Good call.

**Comment by alexmercerind** [comment]
v0.3.5 is released. [Download latest version](https://harmonoid.com/).
