### ISSUE TITLE
Add a default playlist with all the songs.

### ISSUE THREAD

**Issue by pktiuk** [harmonoid/harmonoid#376]
**Describe the new feature you'd like**

By default in the playlists tab we can see two created by default playlists.  

![obraz](https://user-images.githubusercontent.com/45544416/209373003-93cd5146-a882-4b44-871b-2cf2f24911f6.png)

It would be good to add a playlist with all the songs (preferably sorted from the newest ones) to the default playlists.

**Comment by MSOB7YY** [comment]
okay but what's the real point? tracks page has all your music already, wouldn't selection and adding to playlist be more useful in this case?

**Comment by pktiuk** [comment]
> okay but what's the real point?

The real point (at least for me) is just playing all of my music without the need to deal with creating a new temporary queue. Currently it is rather annoying (on PC), because, when I open any song from tracks, I just get a queue with only one song (I have enabled setting `Start playing other music from library after queue`).
![obraz](https://user-images.githubusercontent.com/45544416/209949433-ef21b2ba-4375-4426-8fd8-23bd7b14d46d.png)
Maybe this is a bug?

**Comment by alexmercerind** [comment]
> The real point (at least for me) is just playing all of my music without the need to deal with creating a new temporary queue.

An alternative solution/approach was discussed to this.
I proposed to add a new "Play All" button, which will play all the music present in music library in an ordered manner.

![](https://user-images.githubusercontent.com/28951144/210106575-9270ce14-9892-4321-9f73-82b15445f419.jpg)

It's part of the next release's goals. More details at #348. Harmonoid was under a refactor which kept me really busy, a lot of clean-up & architectural changes have been made. Now I can focus on implementing new things again.

Thanks!

**Comment by alexmercerind** [comment]
"Start playing other music from library after queue":
It makes Harmonoid add other songs from music library (in randomized order) to the queue after playing the selected items.

<hr>

Harmonoid is getting complex for a newcomer. We need docs too. However, I don't think I will ever be able to write those.

**Comment by pktiuk** [comment]
> I proposed to add a new "Play All" button, which will play all the music present in music library in an ordered manner.

I think this functionality is a good replacement to my idea. If you want you can just mark this issue as a duplicate of the issue  focused on implementing `Play All`.

**Comment by alexmercerind** [comment]
v0.3.5 is released. [Download latest version](https://harmonoid.com/).
