### ISSUE TITLE
request: disable GTK header-bar on GNOME

### ISSUE THREAD

**Issue by victormatheusEK** [harmonoid/harmonoid#380]
I use GNOME as my main desktop, and the titlebar for harmonoid is just too thick and don't even have the same collor accent as the application to help make it a little less conspicuous. When I used it on windows, the titlebar and the application had the same color accent, so you wouldn't even know that the titlebar is there.

I have an gnome extension that allows me to hide the titlebar for non-gtk apps like vscode or qbittorrent, but it doesn't work on harmonoid.

Would it be possible to customize it or even hide it?

How it looks when Harmonoid is fullscreen on gnome:
![image](https://user-images.githubusercontent.com/57508095/209567807-5cf87db5-a4f9-4dd4-a820-8d40e03b9c8f.png)

How it looks when vscode is fullscreen:
![image](https://user-images.githubusercontent.com/57508095/209567872-19659af4-1f90-4b04-8dfc-d07fab4da804.png)

**Comment by alexmercerind** [comment]
Hmm... I don't like header-bar either. However, this is the default style for _most_ applications on GNOME.

Refer here in the source code:

https://github.com/harmonoid/harmonoid/blob/b9bf4b60f76537c53e40eaf984712f871102b91e/linux/my_application.cc#L47-L72

Rest, I'm free to hear your opinion about this.

**Comment by Khaledsame** [comment]
Hi , But Seems i've the same problem here.
 -->> (Manjaro Linux x86_64 / Gnome 43.2)
Maybe it's from gnome itself??
![Screenshot from 2022-12-31 16-11-04](https://user-images.githubusercontent.com/94556591/210139591-e5ca5f14-2a0a-4d56-af1d-f82f9ba96548.png)

**Comment by alexmercerind** [comment]
Hi @victormatheusEK & @Khaledsame,

Please [install the latest nightly build](https://github.com/harmonoid/nightly/releases/tag/nightly).
It should not be present anymore.

Since, this is a nightly build, few things might not work as intended (_though I feel it's fairly stable_).
I'm working actively to ensure stability of Harmonoid. Thanks for using it!
Leaving issue opened till next stable release.

<hr>

Thanks! Happy new year! 🎊

**Comment by alexmercerind** [comment]
Just wanted to say that keyboard shortcuts are broken in this build.

**Comment by alexmercerind** [comment]
v0.3.5 is released. [Download latest version](https://harmonoid.com/).

**Comment by victormatheusEK** [comment]
It still have the header-bar.
Currently using PopOS
![image](https://user-images.githubusercontent.com/57508095/210847854-e5553dfa-051e-4de9-9380-4302a7081d76.png)
