### ISSUE TITLE
Bluetooth Audio does not play after app is closed

### ISSUE THREAD

**Issue by soham1sawant** [harmonoid/harmonoid#381]
**Describe the bug**
After I play audio through Bluetooth on the Harmonoid Linux app. When I close it and play any other audio but this time not from the Harmonoid Linux app. The audio is not played. For example, playing a video via VLC media player. To fix the problem I have to unpair the Bluetooth device and pair it again.

**To Reproduce**
1. Connect  Bluetooth audio device to Linux desktop system.
2. Stream audio from YouTube in the Harmonoid Linux app.
3. Close the Harmonoid app. This causes to stop what was playing via the harmonoid app.
4. Now open any video or audio file, but play in any other app, other than harmonoid.
5. There will no audio playing.

**Expected behavior**
After reproducing till step 4 from above. The audio should play.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora Linux 36 (Workstation Edition)
 - Version 36

**Comment by alexmercerind** [comment]
Harmonoid internally uses [libmpv](https://github.com/mpv-player/mpv/tree/master/libmpv) (C API for [mpv](https://github.com/mpv-player/mpv)) for media playback.
If similar issues exist with [mpv](https://github.com/mpv-player/mpv), it will be easy to track down i.e. 
- Connecting to Bluetooth audio.
- Playing a media in [mpv](https://github.com/mpv-player/mpv).
- Closing the [mpv](https://github.com/mpv-player/mpv) process.
- Checking if Bluetooth audio still works.

**Comment by soham1sawant** [comment]
How do I achieve this ?

**Comment by alexmercerind** [comment]
Hi!
Just by playing the media using [mpv](https://mpv.io/) instead of Harmonoid & following same steps you mention.
You likely already have [mpv](https://mpv.io/) on your computer, because it is required by Harmonoid (as a dependency).

```
mpv "/path/to/your/music/file.flac"
```

Thanks!

**Comment by soham1sawant** [comment]
I upgraded my system to Fedora 37 Workstation before testing if the error occurs using mpv also. After testing with both mpv and Harmonoid the bug seems to have gone.
