### ISSUE TITLE
Edit synced lyrics

### ISSUE THREAD

**Issue by venkat2305** [harmonoid/harmonoid#393]
**Describe the new feature you'd like**

An option to edit,copy,paste synced lyrics in the app would be great. Do you plan to add this? 
And some song files have better synced lyrics in itself than that provided by harmonoid. It would be great if we could switch between them.

**Comment by alexmercerind** [comment]
> Do you plan to add this ?

Nope. It is because it's already possible.

Just right click the track & "Select LRC File" / "Clear Selected LRC File". Choose your own LRC file that contains "better" lyrics.
If you want to edit existing, just open the `.Harmonoid/Lyrics/` in your user directory & edit with notepad.

**Comment by venkat2305** [comment]
there is no folder named lyrics 
![image](https://user-images.githubusercontent.com/55329452/212824416-091cb70a-80bb-4cbf-b848-33ca1499a168.png)

**Comment by alexmercerind** [comment]
Not this folder. The one in your user directory.

**Comment by venkat2305** [comment]
I take it back. Harmonoid has the best synced lyrics. Thank you so much for this app.
