### ISSUE TITLE
[Question] Song not displaying on the library 

### ISSUE THREAD

**Issue by SteveeWasTaken** [harmonoid/harmonoid#400]
**Describe the bug**
When loading my library, it loads all my songs, except for one. It's on the same folder as the others, but Harmonoid doesn't display it. This happens in both the Windows app and the Android app.

**To Reproduce**
1. Set a folder to scan.
2. Reindex the library
3. Song doesn't show up along the others

**Expected behavior**
All songs should appear.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v0.3.5

**Smartphone (please complete the following information):**
 - Device: Redmi Note 8
 - OS: Android 12L
 - Version v0.3.5

**Comment by alexmercerind** [comment]
May you please mail me the sample at <alexmercerind@gmail.com>?

Thanks!

**Comment by alexmercerind** [comment]
Hi!

## Problem

It seems the file you shared has size less than 1MB. By default, minimum file size in Harmonoid is 1 MB _i.e._ all files smaller than 1 MB are not indexed. This is done to avoid showing any non-music audio files (which might be present on someone's file-system).

## Solution

So, you can go into the settings & modify the "minimum file size" & hit refresh button.
It'll make the shared file show inside your music library.


<img width="280" src="https://user-images.githubusercontent.com/28951144/217239570-d9501002-9880-465b-8770-5c9892606406.png">
