### ISSUE TITLE
Two similar languages under the same name

### ISSUE THREAD

**Issue by SteveeWasTaken** [harmonoid/harmonoid#401]
**Describe the bug**
When you go to change the language, the list displays "Español" twice. This probably is because there's two different versions, "Español - España", and "Español - Latin America".

**To Reproduce**
1. Go to settings
2. Click on Language
3. Scroll down to "Español"

**Expected behavior**
The list should display "Latin America" and "España" separately.

**Screenshots**
![Screenshot_20230212-154509_Harmonoid](https://user-images.githubusercontent.com/77215030/218336194-3ee23bca-47ae-41a1-88b3-2287d4d18be3.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 8
 - OS: Android 13
 - Version: v0.3.5

**Comment by alexmercerind** [comment]
Part of [v0.3.6](https://github.com/harmonoid/harmonoid/releases/tag/v0.3.6). Thanks!
