### ISSUE TITLE
Missing keybinding

### ISSUE THREAD

**Issue by Itookmyprozac** [harmonoid/harmonoid#403]
**CTRL+Q to exit the app**

I'm using i3wm and the default config of this window manager hides the standard buttons as close, minimize, etc. It's really easy to add an exception to Harmonoid to allow the player to show these buttons but I'd like the have the same patter in my system and its interface.

It's not a critical feature and I'll keep using this fantastic player but It would make it perfect.

**Comment by alexmercerind** [comment]
Hi!

Thanks for the feedback, I just implemented this in the snapshot build. Please try it out.

Now, Ctrl+Q will exit the application. I guess you recommended this on the right time :smile:. Hopefully this will be part of next release now. This build is the next release candidate. You will see some new things in this build e.g. option to change speed or disable animations etc. etc.


https://github.com/harmonoid/snapshots/releases

Please do let me know if you find something broken in this snapshot, I've been polishing things before the release. I try my best to ensure the quality of the software that I put out.

Thanks!

**Comment by Itookmyprozac** [comment]
Perfect! It works like a charm! 

Thanks, alexmercerind :)

**Comment by alexmercerind** [comment]
Part of [v0.3.6](https://github.com/harmonoid/harmonoid/releases/tag/v0.3.6). Thanks!
