### ISSUE TITLE
Load cover art from the folder

### ISSUE THREAD

**Issue by DegreesK0** [harmonoid/harmonoid#406]
I have lots of folders where the cover art is directly downloaded into the folder. However the images do not display in the app.

It'd be great if the app could source and use the images in the folder as the album/cover art.

Thanks.

**Comment by alexmercerind** [comment]
Enable fallback album art from settings.

**Comment by alexmercerind** [comment]
Read this for more:

https://github.com/harmonoid/harmonoid/issues/379#issuecomment-1368275462
