### ISSUE TITLE
Doesn't appear after closing 

### ISSUE THREAD

**Issue by gwapocmacky** [harmonoid/harmonoid#408]
**Describe the bug**
It doesn't let me open the app twice after closing it and it's annoying
I have thousands of songs (mp3) in my folder and I'm wondering if that's the case
even so, I don't think that should be a problem 
Even if I try to reopen it again and again just like what's on the screenshot it still won't open
I have tried forcing stopping it and reopening but that doesn't do it

**To Reproduce**
1. Close the app then open it again more than twice

**Expected behavior**
will open again but no

**Screenshots**
![image](https://user-images.githubusercontent.com/56789900/222140046-f638a553-9fcf-4899-91e7-63066f4119f4.png)

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - 1803

**Comment by alexmercerind** [comment]
It's a single instance application? What exactly are you trying to do?

I can play music perfectly fine both from File Explorer & within Harmonoid's UI.

**Comment by alexmercerind** [comment]
If an existing app process is running, it will be "focused". Terminate all of those (I don't know how you ended up in this state).

**Comment by alexmercerind** [comment]
Wanna say something?

**Comment by gwapocmacky** [comment]
I swear this is a bug that I've been experiencing
here is a clip of that but this time it works when I force close it then reopen (maybe cuz my pc is fresh from booting up?)

https://user-images.githubusercontent.com/56789900/222307714-a13a28e1-9213-47cc-86b5-c4c59568341b.mp4

**Comment by alexmercerind** [comment]
Hi!
Do you happen to use some external third party software for tweaking the default Windows behaviour in one way or another?

**Comment by gwapocmacky** [comment]
I am using a modified version of windows 10 and this is the only thing that I use for third party software
![image](https://user-images.githubusercontent.com/56789900/222328061-4581c429-b09b-49a4-99c1-84a270813314.png)

**Comment by alexmercerind** [comment]
Does latest snapshot build fix it for you?

https://github.com/harmonoid/snapshots/releases/tag/snapshot

**Comment by gwapocmacky** [comment]
https://user-images.githubusercontent.com/56789900/222339485-b95d0486-0b49-446f-91bc-656abb072966.mp4

It's fixed!!

I'm glad that I reported this
Thank youu very much for fixing it
I'll use this version temporarily while waiting for the initial release with this update
**Great work bro!**

**Comment by alexmercerind** [comment]
Part of https://github.com/harmonoid/harmonoid/releases/tag/v0.3.7

Thanks!
