### ISSUE TITLE
Flatpak using end-of-life gnome 41 runtime

### ISSUE THREAD

**Issue by imhemish** [harmonoid/harmonoid#409]
I received the following warnings when installing the app from flathub:
```[hemish@fedora ~]$ flatpak install harmonoid
Looking for matches…
Found ref ‘app/io.github.harmonoid.harmonoid/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: y

Info: app io.github.harmonoid.harmonoid branch stable is end-of-life, with reason:
   The application has been removed from Flathub.
```
I also found out that flatpak is using GNOME Platform 41, which is end-of-life and not supported. In most cases, it should be just fine to change the number from 41 to 43.   
Gnome Platform may not be required at all, and you can just use the lightweight FreeDesktop Platform

**Comment by alexmercerind** [comment]
- Where did I mention that Harmonoid is available on FlatHub?

**Comment by imhemish** [comment]
But It is available there, probably it existed there in past, or someone else uploaded it. In case you don't want it there, or want to maintain it yourself, please file this to flathub admins, because its still installable from flathub.

**Comment by alexmercerind** [comment]
I can't remove that. What I can do is give crystal clear instruction on how to get the application on website. Why dig in?

There are distribution specific packages for RHEL/Fedora or Debian/Ubuntu users & AUR package for Arch users.

**Comment by imhemish** [comment]
I understand that you have given distribution specific packages, but It still is available on FlatHub, and doesnt work correctly (basically playback doesnt work). I don't blame you that the flathub version does not work. But, if it doesn't work, then it should be really removed from there. If you are the core dev of the app, you can request to get it removed, otherwise people like me, who just go straight to flathub to install apps, would experience the same, and then come later at harmonoid's site

**Comment by alexmercerind** [comment]
Skill issue.

**Comment by imhemish** [comment]
> Skill issue.

at whom's side?

**Comment by imhemish** [comment]
I asked Flathub room, and they said that it would be hidden in GUI stores, but would remain like that there if installed through command line. So, ok fine
