### ISSUE TITLE
LastFM

### ISSUE THREAD

**Issue by not-NEKO** [harmonoid/harmonoid#411]
I think a lastfm integration should be awesome to see on harmonoid. I saw a lot of people wanting this kind of feature for a music player.

**Comment by alexmercerind** [comment]
Duplicate: #180.

Thanks for feedback!

**Comment by alexmercerind** [comment]
![](https://github.com/user-attachments/assets/95f4e936-ef3c-4aee-9b3f-029944c19e0d)

Last.fm support has been added in the [latest snapshot](https://github.com/harmonoid/snapshots/releases), it will be part of the next release.

Thanks!
