### ISSUE TITLE
Discord RPC not working on Ubuntu/Linux

### ISSUE THREAD

**Issue by iammilandwl** [harmonoid/harmonoid#414]
**Describe the bug**
When playing a song, it does not show on my discord profile.

**To Reproduce**
1. Go to settings
2. Enable Discord RPC
3. Play a song
4. See nothing 

**Expected behavior**
The song as activity

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/67167142/230216847-8d1175be-0ca4-4545-9b37-ba2ead82e864.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Comment by alexmercerind** [comment]
- Are you using Discord from any web browser?
- Have you installed Discord using snap or FlatHub etc.?

**Comment by iammilandwl** [comment]
Sorry to get to this late. It works now after using another discord install source.
