### ISSUE TITLE
how to make use of `HARMONOID_CACHE_DIR`

### ISSUE THREAD

**Issue by omaru-ok** [harmonoid/harmonoid#416]
**Ask your question here**
this is a question and Feature Request too 

the **V0.3.7 • STABILIZING** Option
- Added support for `HARMONOID_CACHE_DIR ` environment variable to set cache location.
how to make use of it ??
dont say we have to use **$XDG** structure for that 

like in `window` as `powershell`
**$Env:HARMONOID_CACHE_DIR="path/to/folder/"**
no one uses harmonoid from powershell **TBH** 
so wats going on ? 

**REQUEST !**
move `~/.Harmonoid` to somewhere else do not make it clutter with $HOME please 🙏 
i hate this unwanted things showed up in $HOME which don't even has use for USER at all 

**ideas for location**
for .msi install 
`$APPDATA/LOCAL/HARMONOID` or `~/.cache/harmonoid/` -- believe me i use ~/.cache for most of things if i can 
for **`scoop`** install 
**~/scoop/persists/harmonoid**   -> it would be better to handle by scoop this way !

**Comment by alexmercerind** [comment]
Man you can write me on Discord...

**Comment by omaru-ok** [comment]
im not going to say this long paragraph agian on discord

**Comment by alexmercerind** [comment]
![](https://cdn.discordapp.com/attachments/936215182592581653/1091276473433862175/image.png)

**Comment by omaru-ok** [comment]
@alexmercerind i wasn't just asking i was **saying too**
look i have said about REQUEST TOO 
look at it
