### ISSUE TITLE
Audio Quality Distorted

### ISSUE THREAD

**Issue by wodger1912** [harmonoid/harmonoid#422]
**Describe the issue**
Hunted for anyone with similar issue, but to no avail (possible I've pressed something that's balls'd it up)

Audio quality is almost "distorted" if that's the word? - I've recorded an audio clip, same 320K mp3 file played, first half is in Harmonoid, the 2nd half in Lollypop. If you listen closely you can hear Harmonoid section appears to have almost a "poorly adjusted equalizer" (obvious around 20 - 30 second mark). I've looked all over for some setting that could be causing this distortion but can't seem to find anything (and its on all music files played in Harmonoid).

https://www.dropbox.com/s/21bwqbmp4ayy1ci/Harmonoid_Lollypop_Comparison.mp3?dl=0
 
**Attach logs**

1. For Linux:

a) You can get logs by running Harmonoid using terminal.
b) After Harmonoid window opens, click the "REINDEX" button in Settings.
c) Wait for substantial amount of time, until you feel a good amount of information is logged out.
d) Attach the generated logs as file here.

2. For Windows:

You can run Harmonoid using Command Prompt as:

a) First of all, run Command Prompt as Administrator.
b) Type command: harmonoid > logs.txt
c) After Harmonoid window opens, click the "REINDEX" button in Settings.
d) Attach the logs.txt file here.
e) Wait for substantial amount of time, until you feel a good amount of information is added into the logs.txt

3. For Android:

a) Install adb on your computer (Google), enable developer options on your mobile.
b) Attach your phone using USB cable.
e) Run command: adb logcat -s Harmonoid
f) Start Harmonoid on your mobile, click the "REINDEX" button in Settings.
g) Attach logs.

If you are confused about this, please skip & I will help you out.

**Platform (please complete the following information)**

Operating System: Arch Linux 
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.105.0
Qt Version: 5.15.9
Kernel Version: 6.2.11-zen1-1-zen (64-bit)

**App version**

Please confirm that you're on the latest version available.

0.3.7

Cheers,

W.

**Comment by alexmercerind** [comment]
Hi! Have you modified playback speed or pitch from the "Control Panel"?

You can use rubberband audio-filter with Harmonoid. Solution: https://github.com/harmonoid/harmonoid/issues/368#issuecomment-1359001230

**Comment by alexmercerind** [comment]
Will be glad to hear any further feedback :)

**Comment by wodger1912** [comment]
> Hi! Have you modified playback speed or pitch from the "Control Panel"?
> 
> You can use rubberband audio-filter with Harmonoid. Solution: [#368 (comment)](https://github.com/harmonoid/harmonoid/issues/368#issuecomment-1359001230)

Never fiddled with that as far as I can recall, but setting rubberband in the .json file seems to have nailed it now, it sounds much better. If I roll across any other issues, I'll let you know

**Comment by alexmercerind** [comment]
Rubberband is best audio filter that there can be.
