### ISSUE TITLE
[Question][GNU/Linux] No audio

### ISSUE THREAD

**Issue by TenyamaGain** [harmonoid/harmonoid#428]
**Describe the bug**
I have no sound, no audio for any of my .flac files. When I run it in a console, I get the following message/errors
```flutter: No route to host
flutter: #0      IOClient.send (package:http/src/io_client.dart:88)
flutter: <asynchronous suspension>
flutter: #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
flutter: <asynchronous suspension>
flutter: #2      _withClient (package:http/http.dart:164)
flutter: <asynchronous suspension>
flutter: #3      YTMClient.search (package:ytm_client/src/core.dart:14)
flutter: <asynchronous suspension>
flutter: #4      Playback.notifyNativeListeners.<anonymous closure> (package:harmonoid/core/playback.dart:724)
flutter: <asynchronous suspension>
flutter: #5      Playback.notifyNativeListeners (package:harmonoid/core/playback.dart:707)
flutter: <asynchronous suspension>
flutter: 
flutter: No route to host
flutter: #0      IOClient.send (package:http/src/io_client.dart:88)
flutter: <asynchronous suspension>
flutter: #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
flutter: <asynchronous suspension>
flutter: #2      _withClient (package:http/http.dart:164)
flutter: <asynchronous suspension>
flutter: #3      Playback.notifyNativeListeners.<anonymous closure> (package:harmonoid/core/playback.dart:736)
flutter: <asynchronous suspension>
flutter: #4      Playback.notifyNativeListeners (package:harmonoid/core/playback.dart:707)
flutter: <asynchronous suspension>
```

**To Reproduce**
I recently installed Arch Linux, and AUR'd it in, and everything functions perfectly....except no sound.

**Expected behavior**
Sound lol

**Desktop (please complete the following information):**
 - Arch Linux
 - LTS

**Comment by TenyamaGain** [comment]
One thing to mention is, I have apparmor, but when I try --no-sandbox on Harmonoid, it just is an image with a weird gray transparent surface over it, with no functionality.

**Comment by TenyamaGain** [comment]
fixed the "no route" issue -- it was a firewlal issue. Now I'm running into just striaght up no errors

**Comment by alexmercerind** [comment]
You're using YouTube feature right? And... it was working previously.

I have fixed this in the latest snapshot, I will update the stable next week (busy with exams):

https://github.com/harmonoid/snapshots/releases/tag/snapshot

**Comment by alexmercerind** [comment]
Duplicate: #424

**Comment by TenyamaGain** [comment]
This was incorrectly closed. I'm trying to play local .flac files -- not Youtube.

**Comment by TenyamaGain** [comment]
I did, however, try the fix -- to no avail, unfortunately.

**Comment by alexmercerind** [comment]
Does sound work in mpv?

**Comment by alexmercerind** [comment]
Chances are some configuration of your own system is incorrect or messed up. Most issues received from GNU/Linux are like that.

**Comment by TenyamaGain** [comment]
Indeed, you were correct -- trying MPV, it didn't work. So looks like I gotta go down another rabbit hole, because this software you've made is just straight up kickass besides this lol

**Comment by alexmercerind** [comment]
Thanks for the appreciation, looking forward to improvements to the project!

I hope you find out the fault. Also, you can set custom libmpv options for Harmonoid (in case you need):
https://github.com/harmonoid/harmonoid/issues/329#issuecomment-1317144541

**Comment by TenyamaGain** [comment]
Alright -- good news and bad news. I figured out the solution -- I have to add "-ao=pulse" to the end of the mpv to make it play sound -- that's the good news. The bad news is.. When I try to apply that to Harmonoid, when it launches, it just shows an image with a gray transparent block in front, with a little popup on the side. I'm willing to work with you to try to get this to work, due to how amazing it is so far.

**Comment by TenyamaGain** [comment]
Everything works perfectly now! Thank you very much for the help!

**Comment by alexmercerind** [comment]
> When I try to apply that to Harmonoid, when it launches, it just shows an image with a grey transparent block in front...

FYI: That is because Harmonoid picks that argument as a file to play (used in file explorer) etc.
