### ISSUE TITLE
How to stream from YouTube with android app?

### ISSUE THREAD

**Issue by dillfrescott** [harmonoid/harmonoid#450]
I can do it fine on desktop, but there is no stream option on android. Only the option to play from url or local file.

**Comment by alexmercerind** [comment]
It's not possible.

In earlier versions, I did implement YouTube playback for Android...
It became hard to maintain (even more after considering M3 revamp).

Now, only Play Store version is distributed.

[](https://user-images.githubusercontent.com/28951144/230049425-47f9bd5c-20e2-4cdd-b166-a80e8de7f6a6.webm)

**Comment by dillfrescott** [comment]
Darn lol. Thanks anyways though!

**Comment by Kandelai** [comment]
You can always use ViMusic, it is in F-droid.

**Comment by alexmercerind** [comment]
The local music library has been focus of the project for quite some time now. No longer considering any YouTube Music etc. related issues.
