### ISSUE TITLE
Discord invitation

### ISSUE THREAD

**Issue by rusocop** [harmonoid/harmonoid#454]
When I try to click the invitation to the discord server, a message is displayed saying that "invitations are paused for this server"

Is this intentional or not? Can I enter the server if not?

**Comment by alexmercerind** [comment]
Hey man!

I really want to appreciate your support & love for the work that I've done. I'm extremely glad to receive your sponsorship, kind review on Google Play & interest to join Discord.

As you may see, the project is a bit stagnant at the moment.

I'm still very keen on continuing this project e.g. directory view, M3 revamp, code refactor & better codec support for Android etc. However, my time these days is extremely limited, this is my last year in college & I'm working towards my career & can't really give time to my hobby projects as such. I hope to have more time in the near future & continue with higher involvement again.

<hr>

I have re-enabled invites if you wish to join & have a peek inside.

Thanks!

https://discord.gg/2Rc3edFWd8

**Comment by alexmercerind** [comment]
I decided to pause Discord invites since it is indeed time taking to handle bug-reports & feedback from people.
