### ISSUE TITLE
Stream not working anymore

### ISSUE THREAD

**Issue by PardesiCat** [harmonoid/harmonoid#455]
Harmonoid stream from online not working on Linux

even using youtube link also not working

imstalled  from Aur

system Arch linux

https://github.com/harmonoid/harmonoid/assets/55957190/7057a048-2a31-4487-beb2-44c97c6e9e71

**Comment by alexmercerind** [comment]
Apologies, yeah it broke (again) probably due to updates from YouTube / Google. There are many other performance & feature improvements which I'd like to proceed with; currently in immense lack of time.

**Comment by PardesiCat** [comment]
hei its sad to hear  id have much knowledge about programming 

but am putting a suggestion  

there some projets who  used to play songs using project [indivious ](https://invidious.io/)

may be insead of direct youtube / yt music you can try this 

which will try to run via invidious instence

**Comment by PardesiCat** [comment]
@sulaimangari   none of working     check in 2nd line i alredy mention  even  changig to  music.youtube  not working

**Comment by alexmercerind** [comment]
The local music library has been focus of the project for quite some time now. No longer considering any YouTube Music etc. related issues.
