### ISSUE TITLE
No access to music on a network NAS

### ISSUE THREAD

**Issue by SeeDborg** [harmonoid/harmonoid#465]
All of my music is located on a NAS, whenI add the path to the library (\\synology\musique), I can't access it though Harmonoid, and music appears weardly : 

![image](https://github.com/harmonoid/harmonoid/assets/7523821/d17048bd-f9e6-4d63-a0f4-c01d94d50929)

**Comment by SeeDborg** [comment]
Any updates on this issue ?

**Comment by alexmercerind** [comment]
The [latest snapshot](https://github.com/harmonoid/snapshots/releases/snapshot) should solve it.

**Comment by SeeDborg** [comment]
Indeed, thank you very much for the hard work !
