### ISSUE TITLE
Embedded Lyrics not Showing

### ISSUE THREAD

**Issue by t800-x** [harmonoid/harmonoid#473]
Sometimes the app would not show embedded lyrics in flac files. I couldn't notice a pattern to it, it just randomly happens.

There is also an issue with non-synced embedded lyrics. Synced lyrics are in the format [timestamp] - line, but the indexing algorithm tries to do the same for non-synced lyrics, a simple fix would be to check if the first character in the Lyrics tag starts with a '[', if it does then it shall be indexed normally but if it doesn't it should be indexed in a paragraph form instead of the standard key-value pairs.

OS: Windows 11 22H2

**Comment by t800-x** [comment]
Just for clarification, the embedded lyrics sometimes work, sometimes they don't.

**Comment by Red6785** [comment]
Are you certain that Harmonoid reads embedded lyrics at all? I was under the impression it didn't, based on the fact that none of mine are being read. Try clearing the selected LRC file and disabling your internet connection for a moment - I think it might be that you're fetching lyrics from the database and they just align with your embedded stuff well.

**Comment by t800-x** [comment]
> Are you certain that Harmonoid reads embedded lyrics at all? I was under the impression it didn't, based on the fact that none of mine are being read. Try clearing the selected LRC file and disabling your internet connection for a moment - I think it might be that you're fetching lyrics from the database and they just align with your embedded stuff well.

Yeah, I think that might be the case.

**Comment by alexmercerind** [comment]
Yeah, embedded lyrics aren't read in current version. Only .LRC files with same name as file in same folder & the API that we use.

**Comment by alexmercerind** [comment]
The latest snapshot loads embedded lyrics: https://github.com/harmonoid/snapshots/releases/snapshot
