### ISSUE TITLE
Getting error after moving the directory

### ISSUE THREAD

**Issue by WoolenBlanket** [harmonoid/harmonoid#478]
**Describe the bug**
I recently moved my music directory to a different drive, and now I am stuck on this page. There doesn't appear to be a way to access settings and change the Library location. Tried clearing cache and reinstalling after complete removal, but still stuck.

**To Reproduce**
1. Move your music directory to a different drive
2. Open Harmonoid.
3. See error

**Expected behavior**
Open an empty library.

**Screenshots**
![Screenshot 2024-05-16 145540](https://github.com/harmonoid/harmonoid/assets/162562786/5704df33-06af-4844-9a0a-f72d20cfdeb0)

**OS**
Edition	Windows 11 Home
Version	23H2
OS build	22631.3593
Windows Feature Experience Pack 1000.22700.1003.0

**Comment by alexmercerind** [comment]
Please edit C:\Users\XYZ\.Harmonoid\Configuration.JSON & remove that directory.
