### ISSUE TITLE
Not all albums are populating in the library 

### ISSUE THREAD

**Issue by ruralTom** [harmonoid/harmonoid#48]
I think it might be an issue with the app not going deeper than 1 folder level?

My music folder has a bunch of random tracks dumped into it, those aren't showing up. I have folders for each artist and albums folders are nested in each musician's folder - those aren't showing up in my collection either. 

Is this by design, am I doing it wrong?

**Comment by mytja** [comment]
Hello!
Yes, as far as I know, it indexes only in Music folder, no other folders inside/outside of this folder, but we will probably add option to index a whole phone, soon, I guess :sweat_smile: 
Thank you for your support

**Comment by alexmercerind** [comment]
Hi there @ruralTom !

Nice to see you up here.
- Yeah, you are indeed correct, app is intentionally not scanning Music folder recursively. (And it's a one liner fix)
- The musician's folders are also intentionally removed as that wasn't much stable to give to users at that point.

In future:
- You will be able to choose and select custom folder to scan (and it will go to deeper folders).
- You will be able to get time synced lyrics inside the app for all your music.

It's a project, which is still in development. It requires spare time from my schedule, to add & fix things.
Will let you know, once I fix these.

Greetings.

**Comment by ruralTom** [comment]
> Hi there @ruralTom !
> 
> Nice to see you up here.
> 
>     * Yeah, you are indeed correct, app is intentionally not scanning Music folder recursively. (And it's a one liner fix)
> 
>     * The musician's folders are also intentionally removed as that wasn't much stable to give to users at that point.
> 
> 
> In future:
> 
>     * You will be able to choose and select custom folder to scan (and it will go to deeper folders).
> 
>     * You will be able to get time synced lyrics inside the app for all your music.
> 
> 
> It's a project, which is still in development. It requires spare time from my schedule, to add & fix things.
> Will let you know, once I fix these.
> 
> Greetings.

No hurry or nothing ! I can see this is a labor of love.

Thank you.

**Comment by alexmercerind** [comment]
Hi there @ruralTom  !
Thanks for the love, the fix is landed in the latest release.

Checkout here [here](https://github.com/harmonoid/harmonoid/releases/tag/v0.0.4).

**Comment by ruralTom** [comment]
Excellent!  Thank you
