### ISSUE TITLE
Metadata missing when Music library is from WSL

### ISSUE THREAD

**Issue by DakshKK** [harmonoid/harmonoid#487]
**Describe the bug**
Music Library does not load any metadata for WSL folders.

**To Reproduce**
1. Go to Settings
2. Click on 'Add New Folder' under Music Library
3. Add any WSL path
4. Tracks show as path, not with correct metadata

**Expected behavior**
Metadata loads correctly, with track info.

**Screenshots**
![IMG_20240929_160255946](https://github.com/user-attachments/assets/ea70af17-2619-4e19-9735-c4a0d706743a)

**Desktop:**
 - OS: Windows
 - Version: Dev (OS Building 27695.1000)

**Comment by alexmercerind** [comment]
Thanks a lot. I will take a look.

**Comment by alexmercerind** [comment]
May you join us in our Discord... I think our next snapshot will fix it already.

**Comment by DakshKK** [comment]
Amazing, because if I can download the fix right now. It'll be awesome, since I'm off grid next few months then.

Would the snapshot be available soon? Coz I'm without a dev environment to build it for now.

Guess I'll close the issue here then.

**Comment by DakshKK** [comment]
Any update/progress on this?

**Comment by alexmercerind** [comment]
Hi!

I genuinely apologize... There's a bit of time crunch on my end. A lot of things going on at work.

With that being said, there's an ongoing [project rewrite](https://github.com/harmonoid/harmonoid/pull/475), where everything has been massively changed. Since everything has been majorly refactored in that tree, fixing issues in the current stable version is not really worth it. I don't really have time/resources to do a semantic versioning or LTS etc.

**Comment by DakshKK** [comment]
No problem. And thank you so much. I'll follow up on the rewrite, and come back when I do. I wish I could be of any help right now.

And thanks a lot for this amazing product.

**Comment by alexmercerind** [comment]
Also... since everything is written from ground-up, your existing cache will not be used by this version.

**Comment by DakshKK** [comment]
> There's a new snapshot (finally) for Microsoft Windows & GNU/Linux:
> 
> https://github.com/harmonoid/snapshots/releases/snapshot
> 
> I hope this resolves your issues. There's a LOT in this build.

First of all. Thanks a lot for personally updating. In the meanwhile I copied my library because your project is amazing.

Once I'm on land again, I'll pick up the project and contribute where I could as well.

It's been a delight to use this, and thanks a lot. I'll check the new build when I have enough bandwidth to download the release.
