### ISSUE TITLE
Creating Playlist is corrupted

### ISSUE THREAD

**Issue by privelpriv** [harmonoid/harmonoid#49]
Deleting a playlist will make two new empty playlists with the same name.

![Screenshot_20210304-124308](https://user-images.githubusercontent.com/80042119/109959038-3b5a5f00-7ce7-11eb-9b94-6fad5d4aee4a.png)

**Comment by alexmercerind** [comment]
Hi there @privelpriv !

Nice to meet you.

Thanks for your bug report.
I'll ensure this gets resolved in next update.

**Comment by privelpriv** [comment]
Sorry, deleting playlist will double the total number of playlist. I now have like 100/200 playlists 😅😅😅

**Comment by alexmercerind** [comment]
I'm really sorry.

I'm really unaware about what happened to playlists 😅, everyone is telling me about this. 

My apologies. I'll fix it surely.

**Comment by bdlukaa** [comment]
I am no longer experiencing this issue on the latest master

**Comment by mytja** [comment]
I am also not experiencing this issue anymore. I think we should close this issue.

**Comment by alexmercerind** [comment]
Yeah, i fixed this, but i'll close after next stable tag.
