### ISSUE TITLE
YTM Client appears to be not working

### ISSUE THREAD

**Issue by MulverineX** [harmonoid/harmonoid#493]
**Describe the bug**
YouTube Music tracks never load/play

**To Reproduce**
1. Click on '...'
2. Click 'Stream'
3. Search for 'Play tokyo machine'
4. Attempt to play first result
5. Track never starts

**Expected behavior**
The ytm client should resolve the track properly and begin playback

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Build 22631

**Comment by MulverineX** [comment]
I also gave https://github.com/harmonoid/snapshots/releases/tag/snapshot a try, but it looks like YTM is not implemented in the rewrite yet

**Comment by alexmercerind** [comment]
Hi!

The feature is discontinued.
