### ISSUE TITLE
Search all songs from sd and internal storage at once

### ISSUE THREAD

**Issue by visionxStudio** [harmonoid/harmonoid#63]
Could you please add a feature to load all songs from sd and internal storage so that i don't need to change the path all the time. And also add repeat and shuffle option. Thanks in advance

**Comment by alexmercerind** [comment]
Hi @visionxStudio ! 👋
Thanks for your feedback.
I'll make sure to work on it, currently I gave this basic option to change path where app looks for music.
Yeah, shuffle & repeat options are also useful.

**Comment by alexmercerind** [comment]
Now Harmonoid supports adding multiple directories for indexing. Shuffle & repeat is added aswell.

We have entirely redesigned the app now, and Windows & Linux are our primarily supported platforms.

![](https://raw.githubusercontent.com/harmonoid/harmonoid/assets/harmonoid/windows-final-0.jpg)
![](https://raw.githubusercontent.com/harmonoid/harmonoid/assets/harmonoid/android-final-0.jpg)

Hope you'll like it.
