### ISSUE TITLE
Add Linux packages.

### ISSUE THREAD

**Issue by prateekmedia** [harmonoid/harmonoid#75]
**Describe the new feature you'd like**
There is no package available for linux, appimage is a good format to distribute the app.

Here I my appimage github workflow, https://github.com/prateekmedia/flutube/blob/main/.github/workflows/flutterci.yml.

If you will use this then you also have to use https://github.com/prateekmedia/flutube/blob/main/create_appimage.sh script to build appimage.

**Comment by gaetan1903** [comment]
some people don't like appimage 😂 , cause it's not in unix philosophy 😂😂

**Comment by prateekmedia** [comment]
The other formats to consider for packaging can be flatpak(which is also distro independent) or snap(https://flutter.dev/docs/deployment/linux).

A good example of flatpak can be fluffychat, here is the repo https://github.com/flathub/im.fluffychat.fluffychat/

**Comment by alexmercerind** [comment]
Actually not just distribution, but working itself is a big challenge for me as of now.
This Flutter app is merely a frontend, the main library that powers this on Windows is here: https://github.com/harmonoid/libwinmedia. My other library `dart_vlc` which works on Linux is very heavy (libVLC afterall), so I plan to do something better before adding Linux support. 

In other words, playback on Linux hasn't yet been implemented (atleast in a preferred way), I need good format support aswell as network streaming support (for supporting YouTube/Vimeo/Soundcloud) playback. I will be creating another C++ plugin.

**Comment by alexmercerind** [comment]
So, I ported all libraries to linux now... discord rpc, libwinmedia, metadata


And... here we are, fonts aren't looking great on Linux (especially Dark Mode, so hard to read) exactly how i want them to lets see what i can do.

![Screenshot_20210913_114629](https://user-images.githubusercontent.com/28951144/133034028-ce1938df-62a4-44a2-a5e9-5b85728eeabf.png)
![Screenshot_20210913_115158](https://user-images.githubusercontent.com/28951144/133033938-5e722587-a909-46ce-b193-1a1fce919d81.jpg)

**Comment by alexmercerind** [comment]
For now, I have just published debian package (`.deb`).

**Following Linux packages have been added:**
- [x] DEB
- [ ] RPM
- [ ] AppImage
- [ ] FlatPak
- [x] Raw Executable

Thanks to @prateekmedia media, I saw CI in their flutube repo & mine is kinda similar to theirs.

I hope you guys will like it.
Since, Harmonoid uses few shared libraries installed from distro repositories, it was kinda risky to publish AppImage or Flatpak without proper research from my end. Download links are updated on the README. There are few `apt` dependencies.

Thankyou. I hope it came out looking great. Leaving the issue opened until other packages are added by me other other interested people (if so).

![](https://github.com/harmonoid/harmonoid/raw/assets/linux_0.jpg)

**Comment by prateekmedia** [comment]
@alexmercerind we will need 120x120 icon for flatpak to build properly, can you resize the default png in DEBIAN package folder?

**Comment by alexmercerind** [comment]
![harmonoid-120x120](https://user-images.githubusercontent.com/28951144/133508525-e84dab53-1670-43ab-aea2-53a7316df15e.png)

[Download](https://user-images.githubusercontent.com/28951144/133508525-e84dab53-1670-43ab-aea2-53a7316df15e.png).

I believe its quite a midnight for you too. Let's not worry too much! ✨ You're great.

**Comment by prateekmedia** [comment]
@alexmercerind Please update the release to a point release like 0.1.4.1  so to use it as new flatpak base.

**Comment by prateekmedia** [comment]
@alexmercerind Now that flatpak is done ,please add some instructions in readme regardinh how to install this app with it.

https://flathub.org/apps/details/io.github.harmonoid.harmonoid

**Comment by pktiuk** [comment]
What happened with your Flatpak package?

https://flathub.org/apps/details/io.github.harmonoid.harmonoid gives: App Not Found
