### ISSUE TITLE
Certain files cause crash upon parsing. 

### ISSUE THREAD

**Issue by alexmercerind** [harmonoid/harmonoid#76]
**Describe the bug**
Certain media files, not sure which ones at the moment cause crash upon launching the application.

**To Reproduce**
Just starting the application.

**Desktop (please complete the following information):**
Windows 10 v0.1.2+

Please share your file samples here or mail me at <saini123hitesh@gmail.com>.

Your help will be really appreciated.

**Comment by spnda** [comment]
Could also note so nobody forgets:
With a tagged FLAC file I found there's a read access violation at:
https://github.com/harmonoid/flutter_media_metadata/blob/f7773003d97d6310f6aebf2d76bd6a19a65e6955/cxx/metadata_retriever.cpp#L72
This happens to me while scanning/indexing the media library. Some FLAC files work, some don't.

**Comment by alexmercerind** [comment]
Referencing @ufrshubham 's comment here aswell, to track the progress.

Telling what possibly I did wrong, as far as I knew that OGG/OPUS/Vorbis and FLAC followed same album art structure (which needs to be seeked by certain bytes (header) in order to get actual album art buffer). I personally never kept any FLAC samples so I think I should remove that seeking for FLAC files, everything else should go well.

Assume few minutes for the fixes. Will let you guys know, thanks a lot for your time & report.

**Comment by alexmercerind** [comment]
You guys may please grab the latest build from the GitHub actions here: https://github.com/harmonoid/harmonoid/runs/3514231540

![Screenshot 2021-09-04 230010](https://user-images.githubusercontent.com/28951144/132103411-1c745b7e-ed5b-432f-bb62-03b07b0bd8b8.png)

I hope crash won't happen anymore. Let me know if something breaks.

@spnda I also added `cover.jpg` handling hope it works for you.

**Comment by spnda** [comment]
Yeah, indexed 200 tracks already... So far so good!

**Comment by ufrshubham** [comment]
Cool! Just verified all my *.flac tracks. Works flawlessly!
