### ISSUE TITLE
Rewinding missing media crashes

### ISSUE THREAD

**Issue by ilopX** [harmonoid/harmonoid#81]
**Describe the bug**

https://user-images.githubusercontent.com/8049534/133476366-2d8b7f38-29cf-4e34-b204-d42323bae6c0.mp4

**To Reproduce**
1. Run app
2. Click on 'next/previous file'
3. Crash app

**Expected behavior**
Control buttons should be inactive if no media file is selected.

 - Window 10
 - harmonoid v0.1.3

**Comment by alexmercerind** [comment]
Thanks a lot for the report. Let us know if you discover something else to be wrong. This is libwinmedia specific & I'm surprised how I never attempted to do that.

**Comment by alexmercerind** [comment]
Fixed after v0.1.4. Available for download.
