### ISSUE TITLE
Showing CircularProgressIndicator on resize

### ISSUE THREAD

**Issue by ilopX** [harmonoid/harmonoid#85]
https://user-images.githubusercontent.com/8049534/133498127-315fa67b-e478-4d0c-b3c9-4444483d1fba.mp4

**Expected behavior**
Minimize media icon.

 - Window 10
 - Version v0.1.3

**Comment by alexmercerind** [comment]
@ilopX thanks for the report again.

Irrespective of this bug,
do your files contain embedded metadata & album art? If yes, is it something that app isn't able to parse?

Feel free to share the file with us at https://github.com/harmonoid/flutter_media_metadata.

Thanks.

**Comment by prateekmedia** [comment]
@alexmercerind no it's independent of that, you can also reproduce it with youtube music.
