### ISSUE TITLE
WerFault error after closing the app

### ISSUE THREAD

**Issue by ilopX** [harmonoid/harmonoid#87]
https://user-images.githubusercontent.com/8049534/133503600-0c523f9b-ed33-4c38-960e-6a3b992d901a.mp4

- Windows 10
- v0.1.3, v0.1.4

**Comment by alexmercerind** [comment]
I'm also worried about this one, I have just no idea why this happens. Whenever a new C++/WinRT `MediaPlayer` instance is created, then program raises SEGFAULT on quit. Even console apps.

Let's see what to do. This is kinda critical but not usability breaking. Will try to fix soon.
