### ISSUE TITLE
Lyrics server crashes with accents in song titles

### ISSUE THREAD

**Issue by arafatamim** [harmonoid/harmonoid#97]
Not sure if this is the right place to file the bug, but the lyrics server craps out when it encounters accents in the song title.
Try these:
- `Omniprésent Damien Robitaille` -> doesn't work
`Omnipresent Damien Robitaille` -> works
- `Si t'étais là Louane` -> doesn't work
`Si t'etais la Louane` -> works

I tested this with French. Other languages might have similar issues.

**Comment by alexmercerind** [comment]
Can't seem to reproduce now.

Release: https://github.com/harmonoid/harmonoid/releases/tag/v0.2.0

<table>
<tr>
<td>
<img src='https://github.com/harmonoid/harmonoid/raw/assets/linux_full/0.jpeg?raw=true'></img>
</td>
<td>
<img src='https://github.com/harmonoid/harmonoid/raw/assets/linux_full/4.jpeg?raw=true'></img>
</td>
</tr>
</table>
